package com.hummerrisk.base.mapper;

import com.hummerrisk.base.domain.CloudNativeConfigResultLog;
import com.hummerrisk.base.domain.CloudNativeConfigResultLogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CloudNativeConfigResultLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_config_result_log
     *
     * @mbg.generated Sat Aug 20 02:02:31 CST 2022
     */
    long countByExample(CloudNativeConfigResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_config_result_log
     *
     * @mbg.generated Sat Aug 20 02:02:31 CST 2022
     */
    int deleteByExample(CloudNativeConfigResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_config_result_log
     *
     * @mbg.generated Sat Aug 20 02:02:31 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_config_result_log
     *
     * @mbg.generated Sat Aug 20 02:02:31 CST 2022
     */
    int insert(CloudNativeConfigResultLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_config_result_log
     *
     * @mbg.generated Sat Aug 20 02:02:31 CST 2022
     */
    int insertSelective(CloudNativeConfigResultLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_config_result_log
     *
     * @mbg.generated Sat Aug 20 02:02:31 CST 2022
     */
    List<CloudNativeConfigResultLog> selectByExampleWithBLOBs(CloudNativeConfigResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_config_result_log
     *
     * @mbg.generated Sat Aug 20 02:02:31 CST 2022
     */
    List<CloudNativeConfigResultLog> selectByExample(CloudNativeConfigResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_config_result_log
     *
     * @mbg.generated Sat Aug 20 02:02:31 CST 2022
     */
    CloudNativeConfigResultLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_config_result_log
     *
     * @mbg.generated Sat Aug 20 02:02:31 CST 2022
     */
    int updateByExampleSelective(@Param("record") CloudNativeConfigResultLog record, @Param("example") CloudNativeConfigResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_config_result_log
     *
     * @mbg.generated Sat Aug 20 02:02:31 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") CloudNativeConfigResultLog record, @Param("example") CloudNativeConfigResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_config_result_log
     *
     * @mbg.generated Sat Aug 20 02:02:31 CST 2022
     */
    int updateByExample(@Param("record") CloudNativeConfigResultLog record, @Param("example") CloudNativeConfigResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_config_result_log
     *
     * @mbg.generated Sat Aug 20 02:02:31 CST 2022
     */
    int updateByPrimaryKeySelective(CloudNativeConfigResultLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_config_result_log
     *
     * @mbg.generated Sat Aug 20 02:02:31 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(CloudNativeConfigResultLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_config_result_log
     *
     * @mbg.generated Sat Aug 20 02:02:31 CST 2022
     */
    int updateByPrimaryKey(CloudNativeConfigResultLog record);
}
