package com.hummerrisk.base.mapper;

import com.hummerrisk.base.domain.CloudNativeResultLog;
import com.hummerrisk.base.domain.CloudNativeResultLogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CloudNativeResultLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_result_log
     *
     * @mbg.generated Mon Aug 15 20:18:30 CST 2022
     */
    long countByExample(CloudNativeResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_result_log
     *
     * @mbg.generated Mon Aug 15 20:18:30 CST 2022
     */
    int deleteByExample(CloudNativeResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_result_log
     *
     * @mbg.generated Mon Aug 15 20:18:30 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_result_log
     *
     * @mbg.generated Mon Aug 15 20:18:30 CST 2022
     */
    int insert(CloudNativeResultLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_result_log
     *
     * @mbg.generated Mon Aug 15 20:18:30 CST 2022
     */
    int insertSelective(CloudNativeResultLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_result_log
     *
     * @mbg.generated Mon Aug 15 20:18:30 CST 2022
     */
    List<CloudNativeResultLog> selectByExampleWithBLOBs(CloudNativeResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_result_log
     *
     * @mbg.generated Mon Aug 15 20:18:30 CST 2022
     */
    List<CloudNativeResultLog> selectByExample(CloudNativeResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_result_log
     *
     * @mbg.generated Mon Aug 15 20:18:30 CST 2022
     */
    CloudNativeResultLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_result_log
     *
     * @mbg.generated Mon Aug 15 20:18:30 CST 2022
     */
    int updateByExampleSelective(@Param("record") CloudNativeResultLog record, @Param("example") CloudNativeResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_result_log
     *
     * @mbg.generated Mon Aug 15 20:18:30 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") CloudNativeResultLog record, @Param("example") CloudNativeResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_result_log
     *
     * @mbg.generated Mon Aug 15 20:18:30 CST 2022
     */
    int updateByExample(@Param("record") CloudNativeResultLog record, @Param("example") CloudNativeResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_result_log
     *
     * @mbg.generated Mon Aug 15 20:18:30 CST 2022
     */
    int updateByPrimaryKeySelective(CloudNativeResultLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_result_log
     *
     * @mbg.generated Mon Aug 15 20:18:30 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(CloudNativeResultLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_result_log
     *
     * @mbg.generated Mon Aug 15 20:18:30 CST 2022
     */
    int updateByPrimaryKey(CloudNativeResultLog record);
}
