package com.hummerrisk.base.mapper;

import com.hummerrisk.base.domain.CloudNativeSource;
import com.hummerrisk.base.domain.CloudNativeSourceExample;
import com.hummerrisk.base.domain.CloudNativeSourceWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CloudNativeSourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source
     *
     * @mbg.generated Sun Nov 13 00:25:08 CST 2022
     */
    long countByExample(CloudNativeSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source
     *
     * @mbg.generated Sun Nov 13 00:25:08 CST 2022
     */
    int deleteByExample(CloudNativeSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source
     *
     * @mbg.generated Sun Nov 13 00:25:08 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source
     *
     * @mbg.generated Sun Nov 13 00:25:08 CST 2022
     */
    int insert(CloudNativeSourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source
     *
     * @mbg.generated Sun Nov 13 00:25:08 CST 2022
     */
    int insertSelective(CloudNativeSourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source
     *
     * @mbg.generated Sun Nov 13 00:25:08 CST 2022
     */
    List<CloudNativeSourceWithBLOBs> selectByExampleWithBLOBs(CloudNativeSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source
     *
     * @mbg.generated Sun Nov 13 00:25:08 CST 2022
     */
    List<CloudNativeSource> selectByExample(CloudNativeSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source
     *
     * @mbg.generated Sun Nov 13 00:25:08 CST 2022
     */
    CloudNativeSourceWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source
     *
     * @mbg.generated Sun Nov 13 00:25:08 CST 2022
     */
    int updateByExampleSelective(@Param("record") CloudNativeSourceWithBLOBs record, @Param("example") CloudNativeSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source
     *
     * @mbg.generated Sun Nov 13 00:25:08 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") CloudNativeSourceWithBLOBs record, @Param("example") CloudNativeSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source
     *
     * @mbg.generated Sun Nov 13 00:25:08 CST 2022
     */
    int updateByExample(@Param("record") CloudNativeSource record, @Param("example") CloudNativeSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source
     *
     * @mbg.generated Sun Nov 13 00:25:08 CST 2022
     */
    int updateByPrimaryKeySelective(CloudNativeSourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source
     *
     * @mbg.generated Sun Nov 13 00:25:08 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(CloudNativeSourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source
     *
     * @mbg.generated Sun Nov 13 00:25:08 CST 2022
     */
    int updateByPrimaryKey(CloudNativeSource record);
}
