package com.hummerrisk.base.mapper;

import com.hummerrisk.base.domain.CloudScanTaskHistory;
import com.hummerrisk.base.domain.CloudScanTaskHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CloudScanTaskHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_scan_task_history
     *
     * @mbg.generated Sat Jul 02 02:17:49 CST 2022
     */
    long countByExample(CloudScanTaskHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_scan_task_history
     *
     * @mbg.generated Sat Jul 02 02:17:49 CST 2022
     */
    int deleteByExample(CloudScanTaskHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_scan_task_history
     *
     * @mbg.generated Sat Jul 02 02:17:49 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_scan_task_history
     *
     * @mbg.generated Sat Jul 02 02:17:49 CST 2022
     */
    int insert(CloudScanTaskHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_scan_task_history
     *
     * @mbg.generated Sat Jul 02 02:17:49 CST 2022
     */
    int insertSelective(CloudScanTaskHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_scan_task_history
     *
     * @mbg.generated Sat Jul 02 02:17:49 CST 2022
     */
    List<CloudScanTaskHistory> selectByExampleWithBLOBs(CloudScanTaskHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_scan_task_history
     *
     * @mbg.generated Sat Jul 02 02:17:49 CST 2022
     */
    List<CloudScanTaskHistory> selectByExample(CloudScanTaskHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_scan_task_history
     *
     * @mbg.generated Sat Jul 02 02:17:49 CST 2022
     */
    CloudScanTaskHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_scan_task_history
     *
     * @mbg.generated Sat Jul 02 02:17:49 CST 2022
     */
    int updateByExampleSelective(@Param("record") CloudScanTaskHistory record, @Param("example") CloudScanTaskHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_scan_task_history
     *
     * @mbg.generated Sat Jul 02 02:17:49 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") CloudScanTaskHistory record, @Param("example") CloudScanTaskHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_scan_task_history
     *
     * @mbg.generated Sat Jul 02 02:17:49 CST 2022
     */
    int updateByExample(@Param("record") CloudScanTaskHistory record, @Param("example") CloudScanTaskHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_scan_task_history
     *
     * @mbg.generated Sat Jul 02 02:17:49 CST 2022
     */
    int updateByPrimaryKeySelective(CloudScanTaskHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_scan_task_history
     *
     * @mbg.generated Sat Jul 02 02:17:49 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(CloudScanTaskHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_scan_task_history
     *
     * @mbg.generated Sat Jul 02 02:17:49 CST 2022
     */
    int updateByPrimaryKey(CloudScanTaskHistory record);
}