package com.hummerrisk.base.mapper;

import com.hummerrisk.base.domain.CodeResultLog;
import com.hummerrisk.base.domain.CodeResultLogExample;
import com.hummerrisk.base.domain.CodeResultLogWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CodeResultLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    long countByExample(CodeResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int deleteByExample(CodeResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int insert(CodeResultLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int insertSelective(CodeResultLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    List<CodeResultLogWithBLOBs> selectByExampleWithBLOBs(CodeResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    List<CodeResultLog> selectByExample(CodeResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    CodeResultLogWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByExampleSelective(@Param("record") CodeResultLogWithBLOBs record, @Param("example") CodeResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") CodeResultLogWithBLOBs record, @Param("example") CodeResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByExample(@Param("record") CodeResultLog record, @Param("example") CodeResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByPrimaryKeySelective(CodeResultLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(CodeResultLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByPrimaryKey(CodeResultLog record);
}