package com.hummerrisk.base.mapper;

import com.hummerrisk.base.domain.HistoryPackageTaskItemLog;
import com.hummerrisk.base.domain.HistoryPackageTaskItemLogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface HistoryPackageTaskItemLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_package_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    long countByExample(HistoryPackageTaskItemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_package_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    int deleteByExample(HistoryPackageTaskItemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_package_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_package_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    int insert(HistoryPackageTaskItemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_package_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    int insertSelective(HistoryPackageTaskItemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_package_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    List<HistoryPackageTaskItemLog> selectByExampleWithBLOBs(HistoryPackageTaskItemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_package_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    List<HistoryPackageTaskItemLog> selectByExample(HistoryPackageTaskItemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_package_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    HistoryPackageTaskItemLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_package_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    int updateByExampleSelective(@Param("record") HistoryPackageTaskItemLog record, @Param("example") HistoryPackageTaskItemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_package_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") HistoryPackageTaskItemLog record, @Param("example") HistoryPackageTaskItemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_package_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    int updateByExample(@Param("record") HistoryPackageTaskItemLog record, @Param("example") HistoryPackageTaskItemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_package_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    int updateByPrimaryKeySelective(HistoryPackageTaskItemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_package_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(HistoryPackageTaskItemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_package_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    int updateByPrimaryKey(HistoryPackageTaskItemLog record);
}
