package com.hummerrisk.base.mapper;

import com.hummerrisk.base.domain.HistoryServerResultLog;
import com.hummerrisk.base.domain.HistoryServerResultLogExample;
import com.hummerrisk.base.domain.HistoryServerResultLogWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HistoryServerResultLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_server_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    long countByExample(HistoryServerResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_server_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int deleteByExample(HistoryServerResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_server_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_server_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int insert(HistoryServerResultLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_server_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int insertSelective(HistoryServerResultLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_server_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    List<HistoryServerResultLogWithBLOBs> selectByExampleWithBLOBs(HistoryServerResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_server_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    List<HistoryServerResultLog> selectByExample(HistoryServerResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_server_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    HistoryServerResultLogWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_server_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByExampleSelective(@Param("record") HistoryServerResultLogWithBLOBs record, @Param("example") HistoryServerResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_server_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") HistoryServerResultLogWithBLOBs record, @Param("example") HistoryServerResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_server_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByExample(@Param("record") HistoryServerResultLog record, @Param("example") HistoryServerResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_server_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByPrimaryKeySelective(HistoryServerResultLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_server_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(HistoryServerResultLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_server_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByPrimaryKey(HistoryServerResultLog record);
}