package com.hummerrisk.base.mapper;

import com.hummerrisk.base.domain.HistoryCloudTaskLog;
import com.hummerrisk.base.domain.HistoryCloudTaskLogExample;
import com.hummerrisk.base.domain.HistoryCloudTaskLogWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HistoryCloudTaskLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    long countByExample(HistoryCloudTaskLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int deleteByExample(HistoryCloudTaskLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int insert(HistoryCloudTaskLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int insertSelective(HistoryCloudTaskLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    List<HistoryCloudTaskLogWithBLOBs> selectByExampleWithBLOBs(HistoryCloudTaskLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    List<HistoryCloudTaskLog> selectByExample(HistoryCloudTaskLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    HistoryCloudTaskLogWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByExampleSelective(@Param("record") HistoryCloudTaskLogWithBLOBs record, @Param("example") HistoryCloudTaskLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") HistoryCloudTaskLogWithBLOBs record, @Param("example") HistoryCloudTaskLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByExample(@Param("record") HistoryCloudTaskLog record, @Param("example") HistoryCloudTaskLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByPrimaryKeySelective(HistoryCloudTaskLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(HistoryCloudTaskLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByPrimaryKey(HistoryCloudTaskLog record);
}