package com.hummerrisk.base.mapper;

import com.hummerrisk.base.domain.HistoryCloudNativeResultItem;
import com.hummerrisk.base.domain.HistoryCloudNativeResultItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HistoryCloudNativeResultItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_native_result_item
     *
     * @mbg.generated Wed Aug 17 05:15:22 CST 2022
     */
    long countByExample(HistoryCloudNativeResultItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_native_result_item
     *
     * @mbg.generated Wed Aug 17 05:15:22 CST 2022
     */
    int deleteByExample(HistoryCloudNativeResultItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_native_result_item
     *
     * @mbg.generated Wed Aug 17 05:15:22 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_native_result_item
     *
     * @mbg.generated Wed Aug 17 05:15:22 CST 2022
     */
    int insert(HistoryCloudNativeResultItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_native_result_item
     *
     * @mbg.generated Wed Aug 17 05:15:22 CST 2022
     */
    int insertSelective(HistoryCloudNativeResultItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_native_result_item
     *
     * @mbg.generated Wed Aug 17 05:15:22 CST 2022
     */
    List<HistoryCloudNativeResultItem> selectByExampleWithBLOBs(HistoryCloudNativeResultItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_native_result_item
     *
     * @mbg.generated Wed Aug 17 05:15:22 CST 2022
     */
    List<HistoryCloudNativeResultItem> selectByExample(HistoryCloudNativeResultItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_native_result_item
     *
     * @mbg.generated Wed Aug 17 05:15:22 CST 2022
     */
    HistoryCloudNativeResultItem selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_native_result_item
     *
     * @mbg.generated Wed Aug 17 05:15:22 CST 2022
     */
    int updateByExampleSelective(@Param("record") HistoryCloudNativeResultItem record, @Param("example") HistoryCloudNativeResultItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_native_result_item
     *
     * @mbg.generated Wed Aug 17 05:15:22 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") HistoryCloudNativeResultItem record, @Param("example") HistoryCloudNativeResultItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_native_result_item
     *
     * @mbg.generated Wed Aug 17 05:15:22 CST 2022
     */
    int updateByExample(@Param("record") HistoryCloudNativeResultItem record, @Param("example") HistoryCloudNativeResultItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_native_result_item
     *
     * @mbg.generated Wed Aug 17 05:15:22 CST 2022
     */
    int updateByPrimaryKeySelective(HistoryCloudNativeResultItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_native_result_item
     *
     * @mbg.generated Wed Aug 17 05:15:22 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(HistoryCloudNativeResultItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_native_result_item
     *
     * @mbg.generated Wed Aug 17 05:15:22 CST 2022
     */
    int updateByPrimaryKey(HistoryCloudNativeResultItem record);
}