package com.hummerrisk.base.mapper;

import com.hummerrisk.base.domain.HistoryImageTaskItemLog;
import com.hummerrisk.base.domain.HistoryImageTaskItemLogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface HistoryImageTaskItemLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_image_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    long countByExample(HistoryImageTaskItemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_image_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    int deleteByExample(HistoryImageTaskItemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_image_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_image_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    int insert(HistoryImageTaskItemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_image_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    int insertSelective(HistoryImageTaskItemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_image_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    List<HistoryImageTaskItemLog> selectByExampleWithBLOBs(HistoryImageTaskItemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_image_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    List<HistoryImageTaskItemLog> selectByExample(HistoryImageTaskItemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_image_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    HistoryImageTaskItemLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_image_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    int updateByExampleSelective(@Param("record") HistoryImageTaskItemLog record, @Param("example") HistoryImageTaskItemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_image_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") HistoryImageTaskItemLog record, @Param("example") HistoryImageTaskItemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_image_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    int updateByExample(@Param("record") HistoryImageTaskItemLog record, @Param("example") HistoryImageTaskItemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_image_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    int updateByPrimaryKeySelective(HistoryImageTaskItemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_image_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(HistoryImageTaskItemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_image_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    int updateByPrimaryKey(HistoryImageTaskItemLog record);
}
