package com.hummerrisk.base.mapper;

import com.hummerrisk.base.domain.HistoryCloudTaskItemLog;
import com.hummerrisk.base.domain.HistoryCloudTaskItemLogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface HistoryCloudTaskItemLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    long countByExample(HistoryCloudTaskItemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    int deleteByExample(HistoryCloudTaskItemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    int insert(HistoryCloudTaskItemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    int insertSelective(HistoryCloudTaskItemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    List<HistoryCloudTaskItemLog> selectByExampleWithBLOBs(HistoryCloudTaskItemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    List<HistoryCloudTaskItemLog> selectByExample(HistoryCloudTaskItemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    HistoryCloudTaskItemLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    int updateByExampleSelective(@Param("record") HistoryCloudTaskItemLog record, @Param("example") HistoryCloudTaskItemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") HistoryCloudTaskItemLog record, @Param("example") HistoryCloudTaskItemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    int updateByExample(@Param("record") HistoryCloudTaskItemLog record, @Param("example") HistoryCloudTaskItemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    int updateByPrimaryKeySelective(HistoryCloudTaskItemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(HistoryCloudTaskItemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    int updateByPrimaryKey(HistoryCloudTaskItemLog record);
}
