package com.hummerrisk.base.mapper;

import com.hummerrisk.base.domain.HistoryCloudTaskItem;
import com.hummerrisk.base.domain.HistoryCloudTaskItemExample;
import com.hummerrisk.base.domain.HistoryCloudTaskItemWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HistoryCloudTaskItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_item
     *
     * @mbg.generated Thu Jul 21 18:34:03 CST 2022
     */
    long countByExample(HistoryCloudTaskItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_item
     *
     * @mbg.generated Thu Jul 21 18:34:03 CST 2022
     */
    int deleteByExample(HistoryCloudTaskItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_item
     *
     * @mbg.generated Thu Jul 21 18:34:03 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_item
     *
     * @mbg.generated Thu Jul 21 18:34:03 CST 2022
     */
    int insert(HistoryCloudTaskItemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_item
     *
     * @mbg.generated Thu Jul 21 18:34:03 CST 2022
     */
    int insertSelective(HistoryCloudTaskItemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_item
     *
     * @mbg.generated Thu Jul 21 18:34:03 CST 2022
     */
    List<HistoryCloudTaskItemWithBLOBs> selectByExampleWithBLOBs(HistoryCloudTaskItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_item
     *
     * @mbg.generated Thu Jul 21 18:34:03 CST 2022
     */
    List<HistoryCloudTaskItem> selectByExample(HistoryCloudTaskItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_item
     *
     * @mbg.generated Thu Jul 21 18:34:03 CST 2022
     */
    HistoryCloudTaskItemWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_item
     *
     * @mbg.generated Thu Jul 21 18:34:03 CST 2022
     */
    int updateByExampleSelective(@Param("record") HistoryCloudTaskItemWithBLOBs record, @Param("example") HistoryCloudTaskItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_item
     *
     * @mbg.generated Thu Jul 21 18:34:03 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") HistoryCloudTaskItemWithBLOBs record, @Param("example") HistoryCloudTaskItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_item
     *
     * @mbg.generated Thu Jul 21 18:34:03 CST 2022
     */
    int updateByExample(@Param("record") HistoryCloudTaskItem record, @Param("example") HistoryCloudTaskItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_item
     *
     * @mbg.generated Thu Jul 21 18:34:03 CST 2022
     */
    int updateByPrimaryKeySelective(HistoryCloudTaskItemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_item
     *
     * @mbg.generated Thu Jul 21 18:34:03 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(HistoryCloudTaskItemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_task_item
     *
     * @mbg.generated Thu Jul 21 18:34:03 CST 2022
     */
    int updateByPrimaryKey(HistoryCloudTaskItem record);
}