package com.hummerrisk.base.mapper;

import com.hummerrisk.base.domain.ImageTrivyJson;
import com.hummerrisk.base.domain.ImageTrivyJsonExample;
import com.hummerrisk.base.domain.ImageTrivyJsonWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ImageTrivyJsonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_trivy_json
     *
     * @mbg.generated Fri Aug 19 02:49:36 CST 2022
     */
    long countByExample(ImageTrivyJsonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_trivy_json
     *
     * @mbg.generated Fri Aug 19 02:49:36 CST 2022
     */
    int deleteByExample(ImageTrivyJsonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_trivy_json
     *
     * @mbg.generated Fri Aug 19 02:49:36 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_trivy_json
     *
     * @mbg.generated Fri Aug 19 02:49:36 CST 2022
     */
    int insert(ImageTrivyJsonWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_trivy_json
     *
     * @mbg.generated Fri Aug 19 02:49:36 CST 2022
     */
    int insertSelective(ImageTrivyJsonWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_trivy_json
     *
     * @mbg.generated Fri Aug 19 02:49:36 CST 2022
     */
    List<ImageTrivyJsonWithBLOBs> selectByExampleWithBLOBs(ImageTrivyJsonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_trivy_json
     *
     * @mbg.generated Fri Aug 19 02:49:36 CST 2022
     */
    List<ImageTrivyJson> selectByExample(ImageTrivyJsonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_trivy_json
     *
     * @mbg.generated Fri Aug 19 02:49:36 CST 2022
     */
    ImageTrivyJsonWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_trivy_json
     *
     * @mbg.generated Fri Aug 19 02:49:36 CST 2022
     */
    int updateByExampleSelective(@Param("record") ImageTrivyJsonWithBLOBs record, @Param("example") ImageTrivyJsonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_trivy_json
     *
     * @mbg.generated Fri Aug 19 02:49:36 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") ImageTrivyJsonWithBLOBs record, @Param("example") ImageTrivyJsonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_trivy_json
     *
     * @mbg.generated Fri Aug 19 02:49:36 CST 2022
     */
    int updateByExample(@Param("record") ImageTrivyJson record, @Param("example") ImageTrivyJsonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_trivy_json
     *
     * @mbg.generated Fri Aug 19 02:49:36 CST 2022
     */
    int updateByPrimaryKeySelective(ImageTrivyJsonWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_trivy_json
     *
     * @mbg.generated Fri Aug 19 02:49:36 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(ImageTrivyJsonWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_trivy_json
     *
     * @mbg.generated Fri Aug 19 02:49:36 CST 2022
     */
    int updateByPrimaryKey(ImageTrivyJson record);
}
