package com.hummerrisk.base.mapper;

import com.hummerrisk.base.domain.ImageRepoSyncLog;
import com.hummerrisk.base.domain.ImageRepoSyncLogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ImageRepoSyncLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_repo_sync_log
     *
     * @mbg.generated Sun Sep 04 02:29:57 CST 2022
     */
    long countByExample(ImageRepoSyncLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_repo_sync_log
     *
     * @mbg.generated Sun Sep 04 02:29:57 CST 2022
     */
    int deleteByExample(ImageRepoSyncLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_repo_sync_log
     *
     * @mbg.generated Sun Sep 04 02:29:57 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_repo_sync_log
     *
     * @mbg.generated Sun Sep 04 02:29:57 CST 2022
     */
    int insert(ImageRepoSyncLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_repo_sync_log
     *
     * @mbg.generated Sun Sep 04 02:29:57 CST 2022
     */
    int insertSelective(ImageRepoSyncLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_repo_sync_log
     *
     * @mbg.generated Sun Sep 04 02:29:57 CST 2022
     */
    List<ImageRepoSyncLog> selectByExampleWithBLOBs(ImageRepoSyncLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_repo_sync_log
     *
     * @mbg.generated Sun Sep 04 02:29:57 CST 2022
     */
    List<ImageRepoSyncLog> selectByExample(ImageRepoSyncLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_repo_sync_log
     *
     * @mbg.generated Sun Sep 04 02:29:57 CST 2022
     */
    ImageRepoSyncLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_repo_sync_log
     *
     * @mbg.generated Sun Sep 04 02:29:57 CST 2022
     */
    int updateByExampleSelective(@Param("record") ImageRepoSyncLog record, @Param("example") ImageRepoSyncLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_repo_sync_log
     *
     * @mbg.generated Sun Sep 04 02:29:57 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") ImageRepoSyncLog record, @Param("example") ImageRepoSyncLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_repo_sync_log
     *
     * @mbg.generated Sun Sep 04 02:29:57 CST 2022
     */
    int updateByExample(@Param("record") ImageRepoSyncLog record, @Param("example") ImageRepoSyncLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_repo_sync_log
     *
     * @mbg.generated Sun Sep 04 02:29:57 CST 2022
     */
    int updateByPrimaryKeySelective(ImageRepoSyncLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_repo_sync_log
     *
     * @mbg.generated Sun Sep 04 02:29:57 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(ImageRepoSyncLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_repo_sync_log
     *
     * @mbg.generated Sun Sep 04 02:29:57 CST 2022
     */
    int updateByPrimaryKey(ImageRepoSyncLog record);
}
