package com.hummerrisk.base.mapper;

import com.hummerrisk.base.domain.PackageResultLog;
import com.hummerrisk.base.domain.PackageResultLogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PackageResultLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_result_log
     *
     * @mbg.generated Wed Jun 01 22:18:39 CST 2022
     */
    long countByExample(PackageResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_result_log
     *
     * @mbg.generated Wed Jun 01 22:18:39 CST 2022
     */
    int deleteByExample(PackageResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_result_log
     *
     * @mbg.generated Wed Jun 01 22:18:39 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_result_log
     *
     * @mbg.generated Wed Jun 01 22:18:39 CST 2022
     */
    int insert(PackageResultLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_result_log
     *
     * @mbg.generated Wed Jun 01 22:18:39 CST 2022
     */
    int insertSelective(PackageResultLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_result_log
     *
     * @mbg.generated Wed Jun 01 22:18:39 CST 2022
     */
    List<PackageResultLog> selectByExampleWithBLOBs(PackageResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_result_log
     *
     * @mbg.generated Wed Jun 01 22:18:39 CST 2022
     */
    List<PackageResultLog> selectByExample(PackageResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_result_log
     *
     * @mbg.generated Wed Jun 01 22:18:39 CST 2022
     */
    PackageResultLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_result_log
     *
     * @mbg.generated Wed Jun 01 22:18:39 CST 2022
     */
    int updateByExampleSelective(@Param("record") PackageResultLog record, @Param("example") PackageResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_result_log
     *
     * @mbg.generated Wed Jun 01 22:18:39 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") PackageResultLog record, @Param("example") PackageResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_result_log
     *
     * @mbg.generated Wed Jun 01 22:18:39 CST 2022
     */
    int updateByExample(@Param("record") PackageResultLog record, @Param("example") PackageResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_result_log
     *
     * @mbg.generated Wed Jun 01 22:18:39 CST 2022
     */
    int updateByPrimaryKeySelective(PackageResultLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_result_log
     *
     * @mbg.generated Wed Jun 01 22:18:39 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(PackageResultLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_result_log
     *
     * @mbg.generated Wed Jun 01 22:18:39 CST 2022
     */
    int updateByPrimaryKey(PackageResultLog record);
}
