package com.hummerrisk.base.mapper;

import com.hummerrisk.base.domain.ServerResultLog;
import com.hummerrisk.base.domain.ServerResultLogExample;
import com.hummerrisk.base.domain.ServerResultLogWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServerResultLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    long countByExample(ServerResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int deleteByExample(ServerResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int insert(ServerResultLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int insertSelective(ServerResultLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    List<ServerResultLogWithBLOBs> selectByExampleWithBLOBs(ServerResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    List<ServerResultLog> selectByExample(ServerResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    ServerResultLogWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByExampleSelective(@Param("record") ServerResultLogWithBLOBs record, @Param("example") ServerResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") ServerResultLogWithBLOBs record, @Param("example") ServerResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByExample(@Param("record") ServerResultLog record, @Param("example") ServerResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByPrimaryKeySelective(ServerResultLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(ServerResultLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByPrimaryKey(ServerResultLog record);
}