
INSERT INTO `xxl_job_group` (`id`, `app_name`, `title`, `address_type`, `address_list`, `update_time`) VALUES (2, 'hummer-cloud', '混合云检测', 0, '', sysdate());
INSERT INTO `xxl_job_group` (`id`, `app_name`, `title`, `address_type`, `address_list`, `update_time`) VALUES (3, 'hummer-k8s', '云原生检测', 0, '', sysdate());
INSERT INTO `xxl_job_group` (`id`, `app_name`, `title`, `address_type`, `address_list`, `update_time`) VALUES (4, 'hummer-system', '系统管理', 0, '', sysdate());

INSERT INTO `xxl_job_info` (`id`, `job_group`, `job_desc`, `add_time`, `update_time`, `author`, `alarm_email`, `schedule_type`, `schedule_conf`, `misfire_strategy`, `executor_route_strategy`, `executor_handler`, `executor_param`, `executor_block_strategy`, `executor_timeout`, `executor_fail_retry_count`, `glue_type`, `glue_source`, `glue_remark`, `glue_updatetime`, `child_jobid`, `trigger_status`, `trigger_last_time`) VALUES (2, 2, '云资源检测', sysdate(), sysdate(), 'system', '', 'CRON', '0/10 * * * * ? *', 'DO_NOTHING', 'RANDOM', 'cloudTasksJobHandler', '', 'SERIAL_EXECUTION', 300, 5, 'BEAN', '', 'GLUE代码初始化', sysdate(), '', 1, 0);
INSERT INTO `xxl_job_info` (`id`, `job_group`, `job_desc`, `add_time`, `update_time`, `author`, `alarm_email`, `schedule_type`, `schedule_conf`, `misfire_strategy`, `executor_route_strategy`, `executor_handler`, `executor_param`, `executor_block_strategy`, `executor_timeout`, `executor_fail_retry_count`, `glue_type`, `glue_source`, `glue_remark`, `glue_updatetime`, `child_jobid`, `trigger_status`, `trigger_last_time`) VALUES (3, 2, '对象存储', sysdate(), sysdate(), 'system', '', 'CRON', '0/10 * * * * ? *', 'DO_NOTHING', 'RANDOM', 'ossTasksJobHandler', '', 'SERIAL_EXECUTION', 300, 5, 'BEAN', '', 'GLUE代码初始化', sysdate(), '', 1, 0);
INSERT INTO `xxl_job_info` (`id`, `job_group`, `job_desc`, `add_time`, `update_time`, `author`, `alarm_email`, `schedule_type`, `schedule_conf`, `misfire_strategy`, `executor_route_strategy`, `executor_handler`, `executor_param`, `executor_block_strategy`, `executor_timeout`, `executor_fail_retry_count`, `glue_type`, `glue_source`, `glue_remark`, `glue_updatetime`, `child_jobid`, `trigger_status`, `trigger_last_time`) VALUES (4, 2, '云资源同步', sysdate(), sysdate(), 'system', '', 'CRON', '0/10 * * * * ? *', 'DO_NOTHING', 'RANDOM', 'syncResourceTasksJobHandler', '', 'SERIAL_EXECUTION', 300, 5, 'BEAN', '', 'GLUE代码初始化', sysdate(), '', 1, 0);
INSERT INTO `xxl_job_info` (`id`, `job_group`, `job_desc`, `add_time`, `update_time`, `author`, `alarm_email`, `schedule_type`, `schedule_conf`, `misfire_strategy`, `executor_route_strategy`, `executor_handler`, `executor_param`, `executor_block_strategy`, `executor_timeout`, `executor_fail_retry_count`, `glue_type`, `glue_source`, `glue_remark`, `glue_updatetime`, `child_jobid`, `trigger_status`, `trigger_last_time`) VALUES (5, 3, '主机检测', sysdate(), sysdate(), 'system', '', 'CRON', '0/10 * * * * ? *', 'DO_NOTHING', 'RANDOM', 'serverTasksJobHandler', '', 'SERIAL_EXECUTION', 300, 5, 'BEAN', '', 'GLUE代码初始化', sysdate(), '', 1, 0);
INSERT INTO `xxl_job_info` (`id`, `job_group`, `job_desc`, `add_time`, `update_time`, `author`, `alarm_email`, `schedule_type`, `schedule_conf`, `misfire_strategy`, `executor_route_strategy`, `executor_handler`, `executor_param`, `executor_block_strategy`, `executor_timeout`, `executor_fail_retry_count`, `glue_type`, `glue_source`, `glue_remark`, `glue_updatetime`, `child_jobid`, `trigger_status`, `trigger_last_time`) VALUES (6, 3, 'K8s检测', sysdate(), sysdate(), 'system', '', 'CRON', '0/10 * * * * ? *', 'DO_NOTHING', 'RANDOM', 'k8sTasksJobHandler', '', 'SERIAL_EXECUTION', 300, 5, 'BEAN', '', 'GLUE代码初始化', sysdate(), '', 1, 0);
INSERT INTO `xxl_job_info` (`id`, `job_group`, `job_desc`, `add_time`, `update_time`, `author`, `alarm_email`, `schedule_type`, `schedule_conf`, `misfire_strategy`, `executor_route_strategy`, `executor_handler`, `executor_param`, `executor_block_strategy`, `executor_timeout`, `executor_fail_retry_count`, `glue_type`, `glue_source`, `glue_remark`, `glue_updatetime`, `child_jobid`, `trigger_status`, `trigger_last_time`) VALUES (7, 3, '部署检测', sysdate(), sysdate(), 'system', '', 'CRON', '0/10 * * * * ? *', 'DO_NOTHING', 'RANDOM', 'configTasksJobHandler', '', 'SERIAL_EXECUTION', 300, 5, 'BEAN', '', 'GLUE代码初始化', sysdate(), '', 1, 0);
INSERT INTO `xxl_job_info` (`id`, `job_group`, `job_desc`, `add_time`, `update_time`, `author`, `alarm_email`, `schedule_type`, `schedule_conf`, `misfire_strategy`, `executor_route_strategy`, `executor_handler`, `executor_param`, `executor_block_strategy`, `executor_timeout`, `executor_fail_retry_count`, `glue_type`, `glue_source`, `glue_remark`, `glue_updatetime`, `child_jobid`, `trigger_status`, `trigger_last_time`) VALUES (8, 3, '源码检测', sysdate(), sysdate(), 'system', '', 'CRON', '0/10 * * * * ? *', 'DO_NOTHING', 'RANDOM', 'codeTasksJobHandler', '', 'SERIAL_EXECUTION', 300, 5, 'BEAN', '', 'GLUE代码初始化', sysdate(), '', 1, 0);
INSERT INTO `xxl_job_info` (`id`, `job_group`, `job_desc`, `add_time`, `update_time`, `author`, `alarm_email`, `schedule_type`, `schedule_conf`, `misfire_strategy`, `executor_route_strategy`, `executor_handler`, `executor_param`, `executor_block_strategy`, `executor_timeout`, `executor_fail_retry_count`, `glue_type`, `glue_source`, `glue_remark`, `glue_updatetime`, `child_jobid`, `trigger_status`, `trigger_last_time`) VALUES (9, 3, '文件系统检测', sysdate(), sysdate(), 'system', '', 'CRON', '0/10 * * * * ? *', 'DO_NOTHING', 'RANDOM', 'fsTasksJobHandler', '', 'SERIAL_EXECUTION', 300, 5, 'BEAN', '', 'GLUE代码初始化', sysdate(), '', 1, 0);
INSERT INTO `xxl_job_info` (`id`, `job_group`, `job_desc`, `add_time`, `update_time`, `author`, `alarm_email`, `schedule_type`, `schedule_conf`, `misfire_strategy`, `executor_route_strategy`, `executor_handler`, `executor_param`, `executor_block_strategy`, `executor_timeout`, `executor_fail_retry_count`, `glue_type`, `glue_source`, `glue_remark`, `glue_updatetime`, `child_jobid`, `trigger_status`, `trigger_last_time`) VALUES (10, 3, '镜像检测', sysdate(), sysdate(), 'system', '', 'CRON', '0/10 * * * * ? *', 'DO_NOTHING', 'RANDOM', 'imageTasksJobHandler', '', 'SERIAL_EXECUTION', 300, 5, 'BEAN', '', 'GLUE代码初始化', sysdate(), '', 1, 0);
INSERT INTO `xxl_job_info` (`id`, `job_group`, `job_desc`, `add_time`, `update_time`, `author`, `alarm_email`, `schedule_type`, `schedule_conf`, `misfire_strategy`, `executor_route_strategy`, `executor_handler`, `executor_param`, `executor_block_strategy`, `executor_timeout`, `executor_fail_retry_count`, `glue_type`, `glue_source`, `glue_remark`, `glue_updatetime`, `child_jobid`, `trigger_status`, `trigger_last_time`) VALUES (11, 4, '发送消息通知', sysdate(), sysdate(), 'system', '', 'CRON', '0/10 * * * * ? *', 'DO_NOTHING', 'RANDOM', 'noticeTasksJobHandler', '', 'SERIAL_EXECUTION', 300, 5, 'BEAN', '', 'GLUE代码初始化', sysdate(), '', 1, 0);
INSERT INTO `xxl_job_info` (`id`, `job_group`, `job_desc`, `add_time`, `update_time`, `author`, `alarm_email`, `schedule_type`, `schedule_conf`, `misfire_strategy`, `executor_route_strategy`, `executor_handler`, `executor_param`, `executor_block_strategy`, `executor_timeout`, `executor_fail_retry_count`, `glue_type`, `glue_source`, `glue_remark`, `glue_updatetime`, `child_jobid`, `trigger_status`, `trigger_last_time`) VALUES (12, 4, '历史数据统计', sysdate(), sysdate(), 'system', '', 'CRON', '0/10 * * * * ? *', 'DO_NOTHING', 'RANDOM', 'historyTasksJobHandler', '', 'SERIAL_EXECUTION', 300, 5, 'BEAN', '', 'GLUE代码初始化', sysdate(), '', 1, 0);
