/* eslint-disable */
export const TokenKey = "Admin-Token";
export const DEFAULT_LANGUAGE = "default_language";
export const ACCOUNT_ID = "account_id";
export const ACCOUNT_NAME = "account_name";
export const ACCOUNT = "account";
export const K8S_ID = "k8s_id";
export const K8S_NAME = "k8s_name";
export const K8S = "k8s";
export const ROLE_ADMIN = "admin";
export const IsCollapse = "IsCollapse";
export const CURRENT_ACCOUNT = "current_account";
export const REFRESH_SESSION_USER_URL = "user/refresh";
export const DEFAULT = "default";
export const ZH_CN = "zh-CN";
export const ZH_TW = "zh-TW";
export const EN_US = "en-US";

export const severityOptions = [
  {key: '低风险', value: "LowRisk"},
  {key: '中风险', value: "MediumRisk"},
  {key: '高风险', value: "HighRisk"},
  {key: '高危风险', value: "CriticalRisk"},
];
export const REQUEST_HEADERS = [
  {value: "Accept"},
  {value: "Accept-Charset"},
  {value: "Accept-Language"},
  {value: "Accept-Datetime"},
  {value: "Authorization"},
  {value: "Cache-Control"},
  {value: "Connection"},
  {value: "Cookie"},
  {value: "Content-Length"},
  {value: "Content-MD5"},
  {value: "Content-Type"},
  {value: "Date"},
  {value: "Expect"},
  {value: "From"},
  {value: "Host"},
  {value: "If-Match"},
  {value: "If-Modified-Since"},
  {value: "If-None-Match"},
  {value: "If-Range"},
  {value: "If-Unmodified-Since"},
  {value: "Max-Forwards"},
  {value: "Origin"},
  {value: "Pragma"},
  {value: "Proxy-Authorization"},
  {value: "Range"},
  {value: "Referer"},
  {value: "TE"},
  {value: "User-Agent"},
  {value: "Upgrade"},
  {value: "Via"},
  {value: "Warning"}
]

export const RULE_GROUP_IMG = [
  {value: "aliyun-best.png", name: "最佳实践", id: "hummer-aliyun-plugin"},
  {value: "aliyun-pro.png", name: "等保三级", id: "hummer-aliyun-plugin"},
  {value: "aliyun-oss.png", name: "对象存储", id: "hummer-aliyun-plugin"},
  {value: "aliyun-other.png", name: "其他安全", id: "hummer-aliyun-plugin"},
  {value: "aliyun-cis.png", name: "CIS", id: "hummer-aliyun-plugin"},
  {value: "aliyun-gdpr.png", name: "GDPR", id: "hummer-aliyun-plugin"},
  {value: "aliyun-hipaa.png", name: "HIPAA", id: "hummer-aliyun-plugin"},
  {value: "aliyun-iso.png", name: "ISO", id: "hummer-aliyun-plugin"},
  {value: "aliyun-pci.png", name: "PCI", id: "hummer-aliyun-plugin"},
  {value: "aliyun-soc.png", name: "SOC", id: "hummer-aliyun-plugin"},
  {value: "aliyun-custom.png", name: "自定义", id: "hummer-aliyun-plugin"},
  {value: "aws-best.png", name: "最佳实践", id: "hummer-aws-plugin"},
  {value: "aws-pro.png", name: "等保三级", id: "hummer-aws-plugin"},
  {value: "aws-oss.png", name: "对象存储", id: "hummer-aws-plugin"},
  {value: "aws-other.png", name: "其他安全", id: "hummer-aws-plugin"},
  {value: "aws-cis.png", name: "CIS", id: "hummer-aws-plugin"},
  {value: "aws-gdpr.png", name: "GDPR", id: "hummer-aws-plugin"},
  {value: "aws-hipaa.png", name: "HIPAA", id: "hummer-aws-plugin"},
  {value: "aws-iso.png", name: "ISO", id: "hummer-aws-plugin"},
  {value: "aws-pci.png", name: "PCI", id: "hummer-aws-plugin"},
  {value: "aws-soc.png", name: "SOC", id: "hummer-aws-plugin"},
  {value: "aws-custom.png", name: "自定义", id: "hummer-aws-plugin"},
  {value: "azure-best.png", name: "最佳实践", id: "hummer-azure-plugin"},
  {value: "azure-pro.png", name: "等保三级", id: "hummer-azure-plugin"},
  {value: "azure-oss.png", name: "对象存储", id: "hummer-azure-plugin"},
  {value: "azure-other.png", name: "其他安全", id: "hummer-azure-plugin"},
  {value: "azure-cis.png", name: "CIS", id: "hummer-azure-plugin"},
  {value: "azure-gdpr.png", name: "GDPR", id: "hummer-azure-plugin"},
  {value: "azure-hipaa.png", name: "HIPAA", id: "hummer-azure-plugin"},
  {value: "azure-iso.png", name: "ISO", id: "hummer-azure-plugin"},
  {value: "azure-pci.png", name: "PCI", id: "hummer-azure-plugin"},
  {value: "azure-soc.png", name: "SOC", id: "hummer-azure-plugin"},
  {value: "azure-custom.png", name: "自定义", id: "hummer-azure-plugin"},
  {value: "baidu-best.png", name: "最佳实践", id: "hummer-baidu-plugin"},
  {value: "baidu-pro.png", name: "等保三级", id: "hummer-baidu-plugin"},
  {value: "baidu-oss.png", name: "对象存储", id: "hummer-baidu-plugin"},
  {value: "baidu-other.png", name: "其他安全", id: "hummer-baidu-plugin"},
  {value: "baidu-cis.png", name: "CIS", id: "hummer-baidu-plugin"},
  {value: "baidu-gdpr.png", name: "GDPR", id: "hummer-baidu-plugin"},
  {value: "baidu-hipaa.png", name: "HIPAA", id: "hummer-baidu-plugin"},
  {value: "baidu-iso.png", name: "ISO", id: "hummer-baidu-plugin"},
  {value: "baidu-pci.png", name: "PCI", id: "hummer-baidu-plugin"},
  {value: "baidu-soc.png", name: "SOC", id: "hummer-baidu-plugin"},
  {value: "baidu-custom.png", name: "自定义", id: "hummer-baidu-plugin"},
  {value: "gcp-best.png", name: "最佳实践", id: "hummer-gcp-plugin"},
  {value: "gcp-pro.png", name: "等保三级", id: "hummer-gcp-plugin"},
  {value: "gcp-oss.png", name: "对象存储", id: "hummer-gcp-plugin"},
  {value: "gcp-other.png", name: "其他安全", id: "hummer-gcp-plugin"},
  {value: "gcp-cis.png", name: "CIS", id: "hummer-gcp-plugin"},
  {value: "gcp-gdpr.png", name: "GDPR", id: "hummer-gcp-plugin"},
  {value: "gcp-hipaa.png", name: "HIPAA", id: "hummer-gcp-plugin"},
  {value: "gcp-iso.png", name: "ISO", id: "hummer-gcp-plugin"},
  {value: "gcp-pci.png", name: "PCI", id: "hummer-gcp-plugin"},
  {value: "gcp-soc.png", name: "SOC", id: "hummer-gcp-plugin"},
  {value: "gcp-custom.png", name: "自定义", id: "hummer-gcp-plugin"},
  {value: "huawei-best.png", name: "最佳实践", id: "hummer-huawei-plugin"},
  {value: "huawei-pro.png", name: "等保三级", id: "hummer-huawei-plugin"},
  {value: "huawei-oss.png", name: "对象存储", id: "hummer-huawei-plugin"},
  {value: "huawei-other.png", name: "其他安全", id: "hummer-huawei-plugin"},
  {value: "huawei-cis.png", name: "CIS", id: "hummer-huawei-plugin"},
  {value: "huawei-gdpr.png", name: "GDPR", id: "hummer-huawei-plugin"},
  {value: "huawei-hipaa.png", name: "HIPAA", id: "hummer-huawei-plugin"},
  {value: "huawei-iso.png", name: "ISO", id: "hummer-huawei-plugin"},
  {value: "huawei-pci.png", name: "PCI", id: "hummer-huawei-plugin"},
  {value: "huawei-soc.png", name: "SOC", id: "hummer-huawei-plugin"},
  {value: "huawei-custom.png", name: "自定义", id: "hummer-huawei-plugin"},
  {value: "huoshan-best.png", name: "最佳实践", id: "hummer-huoshan-plugin"},
  {value: "huoshan-pro.png", name: "等保三级", id: "hummer-huoshan-plugin"},
  {value: "huoshan-oss.png", name: "对象存储", id: "hummer-huoshan-plugin"},
  {value: "huoshan-other.png", name: "其他安全", id: "hummer-huoshan-plugin"},
  {value: "huoshan-cis.png", name: "CIS", id: "hummer-huoshan-plugin"},
  {value: "huoshan-gdpr.png", name: "GDPR", id: "hummer-huoshan-plugin"},
  {value: "huoshan-hipaa.png", name: "HIPAA", id: "hummer-huoshan-plugin"},
  {value: "huoshan-iso.png", name: "ISO", id: "hummer-huoshan-plugin"},
  {value: "huoshan-pci.png", name: "PCI", id: "hummer-huoshan-plugin"},
  {value: "huoshan-soc.png", name: "SOC", id: "hummer-huoshan-plugin"},
  {value: "huoshan-custom.png", name: "自定义", id: "hummer-huoshan-plugin"},
  {value: "jdcloud-best.png", name: "最佳实践", id: "hummer-jdcloud-plugin"},
  {value: "jdcloud-pro.png", name: "等保三级", id: "hummer-jdcloud-plugin"},
  {value: "jdcloud-oss.png", name: "对象存储", id: "hummer-jdcloud-plugin"},
  {value: "jdcloud-other.png", name: "其他安全", id: "hummer-jdcloud-plugin"},
  {value: "jdcloud-cis.png", name: "CIS", id: "hummer-jdcloud-plugin"},
  {value: "jdcloud-gdpr.png", name: "GDPR", id: "hummer-jdcloud-plugin"},
  {value: "jdcloud-hipaa.png", name: "HIPAA", id: "hummer-jdcloud-plugin"},
  {value: "jdcloud-iso.png", name: "ISO", id: "hummer-jdcloud-plugin"},
  {value: "jdcloud-pci.png", name: "PCI", id: "hummer-jdcloud-plugin"},
  {value: "jdcloud-soc.png", name: "SOC", id: "hummer-jdcloud-plugin"},
  {value: "jdcloud-custom.png", name: "自定义", id: "hummer-jdcloud-plugin"},
  {value: "ksyun-best.png", name: "最佳实践", id: "hummer-ksyun-plugin"},
  {value: "ksyun-pro.png", name: "等保三级", id: "hummer-ksyun-plugin"},
  {value: "ksyun-oss.png", name: "对象存储", id: "hummer-ksyun-plugin"},
  {value: "ksyun-other.png", name: "其他安全", id: "hummer-ksyun-plugin"},
  {value: "ksyun-cis.png", name: "CIS", id: "hummer-ksyun-plugin"},
  {value: "ksyun-gdpr.png", name: "GDPR", id: "hummer-ksyun-plugin"},
  {value: "ksyun-hipaa.png", name: "HIPAA", id: "hummer-ksyun-plugin"},
  {value: "ksyun-iso.png", name: "ISO", id: "hummer-ksyun-plugin"},
  {value: "ksyun-pci.png", name: "PCI", id: "hummer-ksyun-plugin"},
  {value: "ksyun-soc.png", name: "SOC", id: "hummer-ksyun-plugin"},
  {value: "ksyun-custom.png", name: "自定义", id: "hummer-ksyun-plugin"},
  {value: "qingcloud-best.png", name: "最佳实践", id: "hummer-qingcloud-plugin"},
  {value: "qingcloud-pro.png", name: "等保三级", id: "hummer-qingcloud-plugin"},
  {value: "qingcloud-oss.png", name: "对象存储", id: "hummer-qingcloud-plugin"},
  {value: "qingcloud-other.png", name: "其他安全", id: "hummer-qingcloud-plugin"},
  {value: "qingcloud-cis.png", name: "CIS", id: "hummer-qingcloud-plugin"},
  {value: "qingcloud-gdpr.png", name: "GDPR", id: "hummer-qingcloud-plugin"},
  {value: "qingcloud-hipaa.png", name: "HIPAA", id: "hummer-qingcloud-plugin"},
  {value: "qingcloud-iso.png", name: "ISO", id: "hummer-qingcloud-plugin"},
  {value: "qingcloud-pci.png", name: "PCI", id: "hummer-qingcloud-plugin"},
  {value: "qingcloud-soc.png", name: "SOC", id: "hummer-qingcloud-plugin"},
  {value: "qingcloud-custom.png", name: "自定义", id: "hummer-qingcloud-plugin"},
  {value: "qiniu-best.png", name: "最佳实践", id: "hummer-qiniu-plugin"},
  {value: "qiniu-pro.png", name: "等保三级", id: "hummer-qiniu-plugin"},
  {value: "qiniu-oss.png", name: "对象存储", id: "hummer-qiniu-plugin"},
  {value: "qiniu-other.png", name: "其他安全", id: "hummer-qiniu-plugin"},
  {value: "qiniu-cis.png", name: "CIS", id: "hummer-qiniu-plugin"},
  {value: "qiniu-gdpr.png", name: "GDPR", id: "hummer-qiniu-plugin"},
  {value: "qiniu-hipaa.png", name: "HIPAA", id: "hummer-qiniu-plugin"},
  {value: "qiniu-iso.png", name: "ISO", id: "hummer-qiniu-plugin"},
  {value: "qiniu-pci.png", name: "PCI", id: "hummer-qiniu-plugin"},
  {value: "qiniu-soc.png", name: "SOC", id: "hummer-qiniu-plugin"},
  {value: "qiniu-custom.png", name: "自定义", id: "hummer-qiniu-plugin"},
  {value: "tencent-best.png", name: "最佳实践", id: "hummer-qcloud-plugin"},
  {value: "tencent-pro.png", name: "等保三级", id: "hummer-qcloud-plugin"},
  {value: "tencent-oss.png", name: "对象存储", id: "hummer-qcloud-plugin"},
  {value: "tencent-other.png", name: "其他安全", id: "hummer-qcloud-plugin"},
  {value: "tencent-cis.png", name: "CIS", id: "hummer-qcloud-plugin"},
  {value: "tencent-gdpr.png", name: "GDPR", id: "hummer-qcloud-plugin"},
  {value: "tencent-hipaa.png", name: "HIPAA", id: "hummer-qcloud-plugin"},
  {value: "tencent-iso.png", name: "ISO", id: "hummer-qcloud-plugin"},
  {value: "tencent-pci.png", name: "PCI", id: "hummer-qcloud-plugin"},
  {value: "tencent-soc.png", name: "SOC", id: "hummer-qcloud-plugin"},
  {value: "tencent-custom.png", name: "自定义", id: "hummer-qcloud-plugin"},
  {value: "ucloud-best.png", name: "最佳实践", id: "hummer-ucloud-plugin"},
  {value: "ucloud-pro.png", name: "等保三级", id: "hummer-ucloud-plugin"},
  {value: "ucloud-oss.png", name: "对象存储", id: "hummer-ucloud-plugin"},
  {value: "ucloud-other.png", name: "其他安全", id: "hummer-ucloud-plugin"},
  {value: "ucloud-cis.png", name: "CIS", id: "hummer-ucloud-plugin"},
  {value: "ucloud-gdpr.png", name: "GDPR", id: "hummer-ucloud-plugin"},
  {value: "ucloud-hipaa.png", name: "HIPAA", id: "hummer-ucloud-plugin"},
  {value: "ucloud-iso.png", name: "ISO", id: "hummer-ucloud-plugin"},
  {value: "ucloud-pci.png", name: "PCI", id: "hummer-ucloud-plugin"},
  {value: "ucloud-soc.png", name: "SOC", id: "hummer-ucloud-plugin"},
  {value: "ucloud-custom.png", name: "自定义", id: "hummer-ucloud-plugin"},
  {value: "vsphere-pro.png", name: "最佳实践", id: "hummer-vsphere-plugin"},
  {value: "vsphere-other.png", name: "其他安全", id: "hummer-vsphere-plugin"},
  {value: "vsphere-custom.png", name: "自定义", id: "hummer-vsphere-plugin"},
  {value: "openstack-pro.png", name: "最佳实践", id: "hummer-openstack-plugin"},
  {value: "openstack-other.png", name: "其他安全", id: "hummer-openstack-plugin"},
  {value: "openstack-custom.png", name: "自定义", id: "hummer-openstack-plugin"},
  {value: "k8s-cis.png", name: "CIS", id: "hummer-k8s-plugin"},
  {value: "k8s-best.png", name: "最佳实践", id: "hummer-k8s-plugin"},
  {value: "k8s-other.png", name: "其他安全", id: "hummer-k8s-plugin"},
  {value: "k8s-custom.png", name: "自定义", id: "hummer-k8s-plugin"},
  {value: "rancher-cis.png", name: "CIS", id: "hummer-rancher-plugin"},
  {value: "rancher-best.png", name: "最佳实践", id: "hummer-rancher-plugin"},
  {value: "rancher-other.png", name: "其他安全", id: "hummer-rancher-plugin"},
  {value: "rancher-custom.png", name: "自定义", id: "hummer-rancher-plugin"},
  {value: "openshift-cis.png", name: "CIS", id: "hummer-openshift-plugin"},
  {value: "openshift-best.png", name: "最佳实践", id: "hummer-openshift-plugin"},
  {value: "openshift-other.png", name: "其他安全", id: "hummer-openshift-plugin"},
  {value: "openshift-custom.png", name: "自定义", id: "hummer-openshift-plugin"},
  {value: "kubesphere-cis.png", name: "CIS", id: "hummer-kubesphere-plugin"},
  {value: "kubesphere-best.png", name: "最佳实践", id: "hummer-kubesphere-plugin"},
  {value: "kubesphere-other.png", name: "其他安全", id: "hummer-kubesphere-plugin"},
  {value: "kubesphere-custom.png", name: "自定义", id: "hummer-kubesphere-plugin"},
  {value: "server-compliance.png", name: "安全合规", id: "hummer-server-plugin"},
  {value: "server-best.png", name: "最佳实践", id: "hummer-server-plugin"},
  {value: "server-safety.png", name: "其他安全", id: "hummer-server-plugin"},
  {value: "server-other.png", name: "自定义", id: "hummer-server-plugin"},
]

