package com.hummer.common.mapper.domain;

import java.io.Serializable;

public class CloudNativeSourceRbacLink implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_native_source_rbac_link.id
     *
     * @mbg.generated Sun Jan 15 19:47:50 CST 2023
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_native_source_rbac_link.k8s_id
     *
     * @mbg.generated Sun Jan 15 19:47:50 CST 2023
     */
    private String k8sId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_native_source_rbac_link.source
     *
     * @mbg.generated Sun Jan 15 19:47:50 CST 2023
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_native_source_rbac_link.target
     *
     * @mbg.generated Sun Jan 15 19:47:50 CST 2023
     */
    private String target;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_native_source_rbac_link.create_time
     *
     * @mbg.generated Sun Jan 15 19:47:50 CST 2023
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cloud_native_source_rbac_link
     *
     * @mbg.generated Sun Jan 15 19:47:50 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_native_source_rbac_link.id
     *
     * @return the value of cloud_native_source_rbac_link.id
     *
     * @mbg.generated Sun Jan 15 19:47:50 CST 2023
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_native_source_rbac_link.id
     *
     * @param id the value for cloud_native_source_rbac_link.id
     *
     * @mbg.generated Sun Jan 15 19:47:50 CST 2023
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_native_source_rbac_link.k8s_id
     *
     * @return the value of cloud_native_source_rbac_link.k8s_id
     *
     * @mbg.generated Sun Jan 15 19:47:50 CST 2023
     */
    public String getK8sId() {
        return k8sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_native_source_rbac_link.k8s_id
     *
     * @param k8sId the value for cloud_native_source_rbac_link.k8s_id
     *
     * @mbg.generated Sun Jan 15 19:47:50 CST 2023
     */
    public void setK8sId(String k8sId) {
        this.k8sId = k8sId == null ? null : k8sId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_native_source_rbac_link.source
     *
     * @return the value of cloud_native_source_rbac_link.source
     *
     * @mbg.generated Sun Jan 15 19:47:50 CST 2023
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_native_source_rbac_link.source
     *
     * @param source the value for cloud_native_source_rbac_link.source
     *
     * @mbg.generated Sun Jan 15 19:47:50 CST 2023
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_native_source_rbac_link.target
     *
     * @return the value of cloud_native_source_rbac_link.target
     *
     * @mbg.generated Sun Jan 15 19:47:50 CST 2023
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_native_source_rbac_link.target
     *
     * @param target the value for cloud_native_source_rbac_link.target
     *
     * @mbg.generated Sun Jan 15 19:47:50 CST 2023
     */
    public void setTarget(String target) {
        this.target = target == null ? null : target.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_native_source_rbac_link.create_time
     *
     * @return the value of cloud_native_source_rbac_link.create_time
     *
     * @mbg.generated Sun Jan 15 19:47:50 CST 2023
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_native_source_rbac_link.create_time
     *
     * @param createTime the value for cloud_native_source_rbac_link.create_time
     *
     * @mbg.generated Sun Jan 15 19:47:50 CST 2023
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
}
