FROM registry.cn-beijing.aliyuncs.com/hummerrisk/nuclei:v0.8 as nuclei-env

FROM registry.cn-beijing.aliyuncs.com/hummerrisk/prowler:v0.8 as prowler-env

FROM registry.cn-beijing.aliyuncs.com/hummerrisk/xray:v0.8 as xray-env

FROM registry.cn-beijing.aliyuncs.com/hummerrisk/cloud-custodian:v0.8.0

WORKDIR /usr

COPY --from=nuclei-env /usr/local/bin/nuclei /usr/local/bin/nuclei

COPY --from=prowler-env /prowler /prowler

COPY --from=xray-env /opt/hummerrisk/xray/ /opt/hummerrisk/xray/

RUN apt-get install --yes git bash libpcap-dev musl && \
    pip3 install detect-secrets==1.0.3 && \
    curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.36.0 && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install -i /usr/local/aws-cli -b /usr/local/bin && \
    mkdir -p /opt/apps


