FROM registry.cn-beijing.aliyuncs.com/hummerrisk/nuclei:v0.3 as nuclei-env

FROM registry.cn-beijing.aliyuncs.com/hummerrisk/prowler:v0.3 as prowler-env

FROM registry.cn-beijing.aliyuncs.com/hummerrisk/dependency-check:v0.3 as dependency-env

FROM registry.cn-beijing.aliyuncs.com/hummerrisk/xray:v0.3 as xray-env

FROM registry.cn-beijing.aliyuncs.com/hummerrisk/cloud-custodian:v0.3.0

WORKDIR /usr

COPY --from=nuclei-env /usr/local/bin/nuclei /usr/local/bin/nuclei

COPY --from=prowler-env /prowler /prowler

COPY --from=dependency-env /usr/share/dependency-check /usr/share/dependency-check

COPY --from=xray-env /opt/hummerrisk/xray/ /opt/hummerrisk/xray/

RUN curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.31.3
