package com.hummerrisk.base.domain;

import java.io.Serializable;

public class CloudNativeConfigResultItem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_native_config_result_item.id
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_native_config_result_item.result_id
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    private String resultId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_native_config_result_item.type
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_native_config_result_item.item_id
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    private String itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_native_config_result_item.title
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_native_config_result_item.description
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_native_config_result_item.message
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_native_config_result_item.namespace
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    private String namespace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_native_config_result_item.query
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    private String query;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_native_config_result_item.resolution
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    private String resolution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_native_config_result_item.severity
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    private String severity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_native_config_result_item.primary_url
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    private String primaryUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_native_config_result_item.status
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cloud_native_config_result_item
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_native_config_result_item.id
     *
     * @return the value of cloud_native_config_result_item.id
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_native_config_result_item.id
     *
     * @param id the value for cloud_native_config_result_item.id
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_native_config_result_item.result_id
     *
     * @return the value of cloud_native_config_result_item.result_id
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    public String getResultId() {
        return resultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_native_config_result_item.result_id
     *
     * @param resultId the value for cloud_native_config_result_item.result_id
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    public void setResultId(String resultId) {
        this.resultId = resultId == null ? null : resultId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_native_config_result_item.type
     *
     * @return the value of cloud_native_config_result_item.type
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_native_config_result_item.type
     *
     * @param type the value for cloud_native_config_result_item.type
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_native_config_result_item.item_id
     *
     * @return the value of cloud_native_config_result_item.item_id
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_native_config_result_item.item_id
     *
     * @param itemId the value for cloud_native_config_result_item.item_id
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_native_config_result_item.title
     *
     * @return the value of cloud_native_config_result_item.title
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_native_config_result_item.title
     *
     * @param title the value for cloud_native_config_result_item.title
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_native_config_result_item.description
     *
     * @return the value of cloud_native_config_result_item.description
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_native_config_result_item.description
     *
     * @param description the value for cloud_native_config_result_item.description
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_native_config_result_item.message
     *
     * @return the value of cloud_native_config_result_item.message
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_native_config_result_item.message
     *
     * @param message the value for cloud_native_config_result_item.message
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_native_config_result_item.namespace
     *
     * @return the value of cloud_native_config_result_item.namespace
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    public String getNamespace() {
        return namespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_native_config_result_item.namespace
     *
     * @param namespace the value for cloud_native_config_result_item.namespace
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    public void setNamespace(String namespace) {
        this.namespace = namespace == null ? null : namespace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_native_config_result_item.query
     *
     * @return the value of cloud_native_config_result_item.query
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    public String getQuery() {
        return query;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_native_config_result_item.query
     *
     * @param query the value for cloud_native_config_result_item.query
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    public void setQuery(String query) {
        this.query = query == null ? null : query.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_native_config_result_item.resolution
     *
     * @return the value of cloud_native_config_result_item.resolution
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    public String getResolution() {
        return resolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_native_config_result_item.resolution
     *
     * @param resolution the value for cloud_native_config_result_item.resolution
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    public void setResolution(String resolution) {
        this.resolution = resolution == null ? null : resolution.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_native_config_result_item.severity
     *
     * @return the value of cloud_native_config_result_item.severity
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    public String getSeverity() {
        return severity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_native_config_result_item.severity
     *
     * @param severity the value for cloud_native_config_result_item.severity
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    public void setSeverity(String severity) {
        this.severity = severity == null ? null : severity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_native_config_result_item.primary_url
     *
     * @return the value of cloud_native_config_result_item.primary_url
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    public String getPrimaryUrl() {
        return primaryUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_native_config_result_item.primary_url
     *
     * @param primaryUrl the value for cloud_native_config_result_item.primary_url
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    public void setPrimaryUrl(String primaryUrl) {
        this.primaryUrl = primaryUrl == null ? null : primaryUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_native_config_result_item.status
     *
     * @return the value of cloud_native_config_result_item.status
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_native_config_result_item.status
     *
     * @param status the value for cloud_native_config_result_item.status
     *
     * @mbg.generated Wed Aug 31 22:11:02 CST 2022
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}