package com.hummerrisk.base.domain;

import java.io.Serializable;

public class Code implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.id
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.name
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.plugin_icon
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    private String pluginIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.status
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.create_time
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.update_time
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    private Long updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.creator
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.proxy_id
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    private Integer proxyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.sbom_id
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    private String sbomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.sbom_version_id
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    private String sbomVersionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.serverty
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    private String serverty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.credential
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    private String credential;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table code
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.id
     *
     * @return the value of code.id
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.id
     *
     * @param id the value for code.id
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.name
     *
     * @return the value of code.name
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.name
     *
     * @param name the value for code.name
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.plugin_icon
     *
     * @return the value of code.plugin_icon
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    public String getPluginIcon() {
        return pluginIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.plugin_icon
     *
     * @param pluginIcon the value for code.plugin_icon
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    public void setPluginIcon(String pluginIcon) {
        this.pluginIcon = pluginIcon == null ? null : pluginIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.status
     *
     * @return the value of code.status
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.status
     *
     * @param status the value for code.status
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.create_time
     *
     * @return the value of code.create_time
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.create_time
     *
     * @param createTime the value for code.create_time
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.update_time
     *
     * @return the value of code.update_time
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.update_time
     *
     * @param updateTime the value for code.update_time
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.creator
     *
     * @return the value of code.creator
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.creator
     *
     * @param creator the value for code.creator
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.proxy_id
     *
     * @return the value of code.proxy_id
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    public Integer getProxyId() {
        return proxyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.proxy_id
     *
     * @param proxyId the value for code.proxy_id
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    public void setProxyId(Integer proxyId) {
        this.proxyId = proxyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.sbom_id
     *
     * @return the value of code.sbom_id
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    public String getSbomId() {
        return sbomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.sbom_id
     *
     * @param sbomId the value for code.sbom_id
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    public void setSbomId(String sbomId) {
        this.sbomId = sbomId == null ? null : sbomId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.sbom_version_id
     *
     * @return the value of code.sbom_version_id
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    public String getSbomVersionId() {
        return sbomVersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.sbom_version_id
     *
     * @param sbomVersionId the value for code.sbom_version_id
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    public void setSbomVersionId(String sbomVersionId) {
        this.sbomVersionId = sbomVersionId == null ? null : sbomVersionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.serverty
     *
     * @return the value of code.serverty
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    public String getServerty() {
        return serverty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.serverty
     *
     * @param serverty the value for code.serverty
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    public void setServerty(String serverty) {
        this.serverty = serverty == null ? null : serverty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.credential
     *
     * @return the value of code.credential
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    public String getCredential() {
        return credential;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.credential
     *
     * @param credential the value for code.credential
     *
     * @mbg.generated Tue Sep 20 14:51:24 CST 2022
     */
    public void setCredential(String credential) {
        this.credential = credential == null ? null : credential.trim();
    }
}