package com.hummerrisk.base.domain;

import java.io.Serializable;

public class HistoryCloudTaskItem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_cloud_task_item.id
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_cloud_task_item.history_cloud_task_id
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    private String historyCloudTaskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_cloud_task_item.hummer_id
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    private String hummerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_cloud_task_item.resource_type
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    private String resourceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_cloud_task_item.plugin_id
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    private String pluginId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_cloud_task_item.plugin_name
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    private String pluginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_cloud_task_item.plugin_icon
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    private String pluginIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_cloud_task_item.account_id
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_cloud_task_item.region_id
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    private String regionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_cloud_task_item.region_name
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    private String regionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_cloud_task_item.severity
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    private String severity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_cloud_task_item.create_time
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_cloud_task_item.update_time
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    private Long updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_cloud_task_item.resource
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    private String resource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table history_cloud_task_item
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_cloud_task_item.id
     *
     * @return the value of history_cloud_task_item.id
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_cloud_task_item.id
     *
     * @param id the value for history_cloud_task_item.id
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_cloud_task_item.history_cloud_task_id
     *
     * @return the value of history_cloud_task_item.history_cloud_task_id
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public String getHistoryCloudTaskId() {
        return historyCloudTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_cloud_task_item.history_cloud_task_id
     *
     * @param historyCloudTaskId the value for history_cloud_task_item.history_cloud_task_id
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public void setHistoryCloudTaskId(String historyCloudTaskId) {
        this.historyCloudTaskId = historyCloudTaskId == null ? null : historyCloudTaskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_cloud_task_item.hummer_id
     *
     * @return the value of history_cloud_task_item.hummer_id
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public String getHummerId() {
        return hummerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_cloud_task_item.hummer_id
     *
     * @param hummerId the value for history_cloud_task_item.hummer_id
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public void setHummerId(String hummerId) {
        this.hummerId = hummerId == null ? null : hummerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_cloud_task_item.resource_type
     *
     * @return the value of history_cloud_task_item.resource_type
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_cloud_task_item.resource_type
     *
     * @param resourceType the value for history_cloud_task_item.resource_type
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType == null ? null : resourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_cloud_task_item.plugin_id
     *
     * @return the value of history_cloud_task_item.plugin_id
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public String getPluginId() {
        return pluginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_cloud_task_item.plugin_id
     *
     * @param pluginId the value for history_cloud_task_item.plugin_id
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public void setPluginId(String pluginId) {
        this.pluginId = pluginId == null ? null : pluginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_cloud_task_item.plugin_name
     *
     * @return the value of history_cloud_task_item.plugin_name
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public String getPluginName() {
        return pluginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_cloud_task_item.plugin_name
     *
     * @param pluginName the value for history_cloud_task_item.plugin_name
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public void setPluginName(String pluginName) {
        this.pluginName = pluginName == null ? null : pluginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_cloud_task_item.plugin_icon
     *
     * @return the value of history_cloud_task_item.plugin_icon
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public String getPluginIcon() {
        return pluginIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_cloud_task_item.plugin_icon
     *
     * @param pluginIcon the value for history_cloud_task_item.plugin_icon
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public void setPluginIcon(String pluginIcon) {
        this.pluginIcon = pluginIcon == null ? null : pluginIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_cloud_task_item.account_id
     *
     * @return the value of history_cloud_task_item.account_id
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_cloud_task_item.account_id
     *
     * @param accountId the value for history_cloud_task_item.account_id
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_cloud_task_item.region_id
     *
     * @return the value of history_cloud_task_item.region_id
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_cloud_task_item.region_id
     *
     * @param regionId the value for history_cloud_task_item.region_id
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId == null ? null : regionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_cloud_task_item.region_name
     *
     * @return the value of history_cloud_task_item.region_name
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_cloud_task_item.region_name
     *
     * @param regionName the value for history_cloud_task_item.region_name
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName == null ? null : regionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_cloud_task_item.severity
     *
     * @return the value of history_cloud_task_item.severity
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public String getSeverity() {
        return severity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_cloud_task_item.severity
     *
     * @param severity the value for history_cloud_task_item.severity
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public void setSeverity(String severity) {
        this.severity = severity == null ? null : severity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_cloud_task_item.create_time
     *
     * @return the value of history_cloud_task_item.create_time
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_cloud_task_item.create_time
     *
     * @param createTime the value for history_cloud_task_item.create_time
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_cloud_task_item.update_time
     *
     * @return the value of history_cloud_task_item.update_time
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_cloud_task_item.update_time
     *
     * @param updateTime the value for history_cloud_task_item.update_time
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_cloud_task_item.resource
     *
     * @return the value of history_cloud_task_item.resource
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public String getResource() {
        return resource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_cloud_task_item.resource
     *
     * @param resource the value for history_cloud_task_item.resource
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public void setResource(String resource) {
        this.resource = resource == null ? null : resource.trim();
    }
}