package com.hummerrisk.base.domain;

import java.io.Serializable;

public class HistoryCloudTaskItemLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_cloud_task_item_log.id
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_cloud_task_item_log.history_cloud_task_id
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    private String historyCloudTaskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_cloud_task_item_log.history_cloud_task_item_id
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    private String historyCloudTaskItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_cloud_task_item_log.create_time
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_cloud_task_item_log.operator
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_cloud_task_item_log.operation
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    private String operation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_cloud_task_item_log.result
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    private Boolean result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_cloud_task_item_log.output
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    private String output;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table history_cloud_task_item_log
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_cloud_task_item_log.id
     *
     * @return the value of history_cloud_task_item_log.id
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_cloud_task_item_log.id
     *
     * @param id the value for history_cloud_task_item_log.id
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_cloud_task_item_log.history_cloud_task_id
     *
     * @return the value of history_cloud_task_item_log.history_cloud_task_id
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public String getHistoryCloudTaskId() {
        return historyCloudTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_cloud_task_item_log.history_cloud_task_id
     *
     * @param historyCloudTaskId the value for history_cloud_task_item_log.history_cloud_task_id
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public void setHistoryCloudTaskId(String historyCloudTaskId) {
        this.historyCloudTaskId = historyCloudTaskId == null ? null : historyCloudTaskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_cloud_task_item_log.history_cloud_task_item_id
     *
     * @return the value of history_cloud_task_item_log.history_cloud_task_item_id
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public String getHistoryCloudTaskItemId() {
        return historyCloudTaskItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_cloud_task_item_log.history_cloud_task_item_id
     *
     * @param historyCloudTaskItemId the value for history_cloud_task_item_log.history_cloud_task_item_id
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public void setHistoryCloudTaskItemId(String historyCloudTaskItemId) {
        this.historyCloudTaskItemId = historyCloudTaskItemId == null ? null : historyCloudTaskItemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_cloud_task_item_log.create_time
     *
     * @return the value of history_cloud_task_item_log.create_time
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_cloud_task_item_log.create_time
     *
     * @param createTime the value for history_cloud_task_item_log.create_time
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_cloud_task_item_log.operator
     *
     * @return the value of history_cloud_task_item_log.operator
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_cloud_task_item_log.operator
     *
     * @param operator the value for history_cloud_task_item_log.operator
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_cloud_task_item_log.operation
     *
     * @return the value of history_cloud_task_item_log.operation
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public String getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_cloud_task_item_log.operation
     *
     * @param operation the value for history_cloud_task_item_log.operation
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public void setOperation(String operation) {
        this.operation = operation == null ? null : operation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_cloud_task_item_log.result
     *
     * @return the value of history_cloud_task_item_log.result
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public Boolean getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_cloud_task_item_log.result
     *
     * @param result the value for history_cloud_task_item_log.result
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public void setResult(Boolean result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_cloud_task_item_log.output
     *
     * @return the value of history_cloud_task_item_log.output
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public String getOutput() {
        return output;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_cloud_task_item_log.output
     *
     * @param output the value for history_cloud_task_item_log.output
     *
     * @mbg.generated Tue Jul 19 04:14:43 CST 2022
     */
    public void setOutput(String output) {
        this.output = output == null ? null : output.trim();
    }
}