package com.hummerrisk.base.domain;

import java.io.Serializable;

public class ImageGrypeTable implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_grype_table.id
     *
     * @mbg.generated Sun Jul 24 02:46:37 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_grype_table.result_id
     *
     * @mbg.generated Sun Jul 24 02:46:37 CST 2022
     */
    private String resultId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_grype_table.name
     *
     * @mbg.generated Sun Jul 24 02:46:37 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_grype_table.installed
     *
     * @mbg.generated Sun Jul 24 02:46:37 CST 2022
     */
    private String installed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_grype_table.fixed_in
     *
     * @mbg.generated Sun Jul 24 02:46:37 CST 2022
     */
    private String fixedIn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_grype_table.type
     *
     * @mbg.generated Sun Jul 24 02:46:37 CST 2022
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_grype_table.vulnerability
     *
     * @mbg.generated Sun Jul 24 02:46:37 CST 2022
     */
    private String vulnerability;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_grype_table.severity
     *
     * @mbg.generated Sun Jul 24 02:46:37 CST 2022
     */
    private String severity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table image_grype_table
     *
     * @mbg.generated Sun Jul 24 02:46:37 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_grype_table.id
     *
     * @return the value of image_grype_table.id
     *
     * @mbg.generated Sun Jul 24 02:46:37 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_grype_table.id
     *
     * @param id the value for image_grype_table.id
     *
     * @mbg.generated Sun Jul 24 02:46:37 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_grype_table.result_id
     *
     * @return the value of image_grype_table.result_id
     *
     * @mbg.generated Sun Jul 24 02:46:37 CST 2022
     */
    public String getResultId() {
        return resultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_grype_table.result_id
     *
     * @param resultId the value for image_grype_table.result_id
     *
     * @mbg.generated Sun Jul 24 02:46:37 CST 2022
     */
    public void setResultId(String resultId) {
        this.resultId = resultId == null ? null : resultId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_grype_table.name
     *
     * @return the value of image_grype_table.name
     *
     * @mbg.generated Sun Jul 24 02:46:37 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_grype_table.name
     *
     * @param name the value for image_grype_table.name
     *
     * @mbg.generated Sun Jul 24 02:46:37 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_grype_table.installed
     *
     * @return the value of image_grype_table.installed
     *
     * @mbg.generated Sun Jul 24 02:46:37 CST 2022
     */
    public String getInstalled() {
        return installed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_grype_table.installed
     *
     * @param installed the value for image_grype_table.installed
     *
     * @mbg.generated Sun Jul 24 02:46:37 CST 2022
     */
    public void setInstalled(String installed) {
        this.installed = installed == null ? null : installed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_grype_table.fixed_in
     *
     * @return the value of image_grype_table.fixed_in
     *
     * @mbg.generated Sun Jul 24 02:46:37 CST 2022
     */
    public String getFixedIn() {
        return fixedIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_grype_table.fixed_in
     *
     * @param fixedIn the value for image_grype_table.fixed_in
     *
     * @mbg.generated Sun Jul 24 02:46:37 CST 2022
     */
    public void setFixedIn(String fixedIn) {
        this.fixedIn = fixedIn == null ? null : fixedIn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_grype_table.type
     *
     * @return the value of image_grype_table.type
     *
     * @mbg.generated Sun Jul 24 02:46:37 CST 2022
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_grype_table.type
     *
     * @param type the value for image_grype_table.type
     *
     * @mbg.generated Sun Jul 24 02:46:37 CST 2022
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_grype_table.vulnerability
     *
     * @return the value of image_grype_table.vulnerability
     *
     * @mbg.generated Sun Jul 24 02:46:37 CST 2022
     */
    public String getVulnerability() {
        return vulnerability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_grype_table.vulnerability
     *
     * @param vulnerability the value for image_grype_table.vulnerability
     *
     * @mbg.generated Sun Jul 24 02:46:37 CST 2022
     */
    public void setVulnerability(String vulnerability) {
        this.vulnerability = vulnerability == null ? null : vulnerability.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_grype_table.severity
     *
     * @return the value of image_grype_table.severity
     *
     * @mbg.generated Sun Jul 24 02:46:37 CST 2022
     */
    public String getSeverity() {
        return severity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_grype_table.severity
     *
     * @param severity the value for image_grype_table.severity
     *
     * @mbg.generated Sun Jul 24 02:46:37 CST 2022
     */
    public void setSeverity(String severity) {
        this.severity = severity == null ? null : severity.trim();
    }
}