package com.hummerrisk.base.domain;

import java.io.Serializable;

public class ImageRepoSyncLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_repo_sync_log.id
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_repo_sync_log.repo_id
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    private String repoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_repo_sync_log.create_time
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_repo_sync_log.operator
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_repo_sync_log.sum
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    private Long sum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_repo_sync_log.result
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    private Boolean result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table image_repo_sync_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_repo_sync_log.id
     *
     * @return the value of image_repo_sync_log.id
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_repo_sync_log.id
     *
     * @param id the value for image_repo_sync_log.id
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_repo_sync_log.repo_id
     *
     * @return the value of image_repo_sync_log.repo_id
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    public String getRepoId() {
        return repoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_repo_sync_log.repo_id
     *
     * @param repoId the value for image_repo_sync_log.repo_id
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    public void setRepoId(String repoId) {
        this.repoId = repoId == null ? null : repoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_repo_sync_log.create_time
     *
     * @return the value of image_repo_sync_log.create_time
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_repo_sync_log.create_time
     *
     * @param createTime the value for image_repo_sync_log.create_time
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_repo_sync_log.operator
     *
     * @return the value of image_repo_sync_log.operator
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_repo_sync_log.operator
     *
     * @param operator the value for image_repo_sync_log.operator
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_repo_sync_log.sum
     *
     * @return the value of image_repo_sync_log.sum
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    public Long getSum() {
        return sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_repo_sync_log.sum
     *
     * @param sum the value for image_repo_sync_log.sum
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    public void setSum(Long sum) {
        this.sum = sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_repo_sync_log.result
     *
     * @return the value of image_repo_sync_log.result
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    public Boolean getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_repo_sync_log.result
     *
     * @param result the value for image_repo_sync_log.result
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    public void setResult(Boolean result) {
        this.result = result;
    }
}