package com.hummerrisk.base.domain;

import java.io.Serializable;

public class TaskItemResourceLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_item_resource_log.id
     *
     * @mbg.generated Sun Jul 17 16:56:40 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_item_resource_log.task_item_id
     *
     * @mbg.generated Sun Jul 17 16:56:40 CST 2022
     */
    private String taskItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_item_resource_log.task_item_resource_id
     *
     * @mbg.generated Sun Jul 17 16:56:40 CST 2022
     */
    private String taskItemResourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_item_resource_log.resource_id
     *
     * @mbg.generated Sun Jul 17 16:56:40 CST 2022
     */
    private String resourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_item_resource_log.create_time
     *
     * @mbg.generated Sun Jul 17 16:56:40 CST 2022
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_item_resource_log.operator
     *
     * @mbg.generated Sun Jul 17 16:56:40 CST 2022
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_item_resource_log.operation
     *
     * @mbg.generated Sun Jul 17 16:56:40 CST 2022
     */
    private String operation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_item_resource_log.result
     *
     * @mbg.generated Sun Jul 17 16:56:40 CST 2022
     */
    private Boolean result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_item_resource_log.output
     *
     * @mbg.generated Sun Jul 17 16:56:40 CST 2022
     */
    private String output;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_item_resource_log
     *
     * @mbg.generated Sun Jul 17 16:56:40 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_item_resource_log.id
     *
     * @return the value of task_item_resource_log.id
     *
     * @mbg.generated Sun Jul 17 16:56:40 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_item_resource_log.id
     *
     * @param id the value for task_item_resource_log.id
     *
     * @mbg.generated Sun Jul 17 16:56:40 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_item_resource_log.task_item_id
     *
     * @return the value of task_item_resource_log.task_item_id
     *
     * @mbg.generated Sun Jul 17 16:56:40 CST 2022
     */
    public String getTaskItemId() {
        return taskItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_item_resource_log.task_item_id
     *
     * @param taskItemId the value for task_item_resource_log.task_item_id
     *
     * @mbg.generated Sun Jul 17 16:56:40 CST 2022
     */
    public void setTaskItemId(String taskItemId) {
        this.taskItemId = taskItemId == null ? null : taskItemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_item_resource_log.task_item_resource_id
     *
     * @return the value of task_item_resource_log.task_item_resource_id
     *
     * @mbg.generated Sun Jul 17 16:56:40 CST 2022
     */
    public String getTaskItemResourceId() {
        return taskItemResourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_item_resource_log.task_item_resource_id
     *
     * @param taskItemResourceId the value for task_item_resource_log.task_item_resource_id
     *
     * @mbg.generated Sun Jul 17 16:56:40 CST 2022
     */
    public void setTaskItemResourceId(String taskItemResourceId) {
        this.taskItemResourceId = taskItemResourceId == null ? null : taskItemResourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_item_resource_log.resource_id
     *
     * @return the value of task_item_resource_log.resource_id
     *
     * @mbg.generated Sun Jul 17 16:56:40 CST 2022
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_item_resource_log.resource_id
     *
     * @param resourceId the value for task_item_resource_log.resource_id
     *
     * @mbg.generated Sun Jul 17 16:56:40 CST 2022
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId == null ? null : resourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_item_resource_log.create_time
     *
     * @return the value of task_item_resource_log.create_time
     *
     * @mbg.generated Sun Jul 17 16:56:40 CST 2022
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_item_resource_log.create_time
     *
     * @param createTime the value for task_item_resource_log.create_time
     *
     * @mbg.generated Sun Jul 17 16:56:40 CST 2022
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_item_resource_log.operator
     *
     * @return the value of task_item_resource_log.operator
     *
     * @mbg.generated Sun Jul 17 16:56:40 CST 2022
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_item_resource_log.operator
     *
     * @param operator the value for task_item_resource_log.operator
     *
     * @mbg.generated Sun Jul 17 16:56:40 CST 2022
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_item_resource_log.operation
     *
     * @return the value of task_item_resource_log.operation
     *
     * @mbg.generated Sun Jul 17 16:56:40 CST 2022
     */
    public String getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_item_resource_log.operation
     *
     * @param operation the value for task_item_resource_log.operation
     *
     * @mbg.generated Sun Jul 17 16:56:40 CST 2022
     */
    public void setOperation(String operation) {
        this.operation = operation == null ? null : operation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_item_resource_log.result
     *
     * @return the value of task_item_resource_log.result
     *
     * @mbg.generated Sun Jul 17 16:56:40 CST 2022
     */
    public Boolean getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_item_resource_log.result
     *
     * @param result the value for task_item_resource_log.result
     *
     * @mbg.generated Sun Jul 17 16:56:40 CST 2022
     */
    public void setResult(Boolean result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_item_resource_log.output
     *
     * @return the value of task_item_resource_log.output
     *
     * @mbg.generated Sun Jul 17 16:56:40 CST 2022
     */
    public String getOutput() {
        return output;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_item_resource_log.output
     *
     * @param output the value for task_item_resource_log.output
     *
     * @mbg.generated Sun Jul 17 16:56:40 CST 2022
     */
    public void setOutput(String output) {
        this.output = output == null ? null : output.trim();
    }
}