package com.hummer.system.mapper;

import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface HistoryCloudNativeResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_native_result
     *
     * @mbg.generated Thu Apr 13 02:39:48 CST 2023
     */
    long countByExample(HistoryCloudNativeResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_native_result
     *
     * @mbg.generated Thu Apr 13 02:39:48 CST 2023
     */
    int deleteByExample(HistoryCloudNativeResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_native_result
     *
     * @mbg.generated Thu Apr 13 02:39:48 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_native_result
     *
     * @mbg.generated Thu Apr 13 02:39:48 CST 2023
     */
    int insert(HistoryCloudNativeResultWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_native_result
     *
     * @mbg.generated Thu Apr 13 02:39:48 CST 2023
     */
    int insertSelective(HistoryCloudNativeResultWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_native_result
     *
     * @mbg.generated Thu Apr 13 02:39:48 CST 2023
     */
    List<HistoryCloudNativeResultWithBLOBs> selectByExampleWithBLOBs(HistoryCloudNativeResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_native_result
     *
     * @mbg.generated Thu Apr 13 02:39:48 CST 2023
     */
    List<HistoryCloudNativeResult> selectByExample(HistoryCloudNativeResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_native_result
     *
     * @mbg.generated Thu Apr 13 02:39:48 CST 2023
     */
    HistoryCloudNativeResultWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_native_result
     *
     * @mbg.generated Thu Apr 13 02:39:48 CST 2023
     */
    int updateByExampleSelective(@Param("record") HistoryCloudNativeResultWithBLOBs record, @Param("example") HistoryCloudNativeResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_native_result
     *
     * @mbg.generated Thu Apr 13 02:39:48 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") HistoryCloudNativeResultWithBLOBs record, @Param("example") HistoryCloudNativeResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_native_result
     *
     * @mbg.generated Thu Apr 13 02:39:48 CST 2023
     */
    int updateByExample(@Param("record") HistoryCloudNativeResult record, @Param("example") HistoryCloudNativeResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_native_result
     *
     * @mbg.generated Thu Apr 13 02:39:48 CST 2023
     */
    int updateByPrimaryKeySelective(HistoryCloudNativeResultWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_native_result
     *
     * @mbg.generated Thu Apr 13 02:39:48 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(HistoryCloudNativeResultWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_cloud_native_result
     *
     * @mbg.generated Thu Apr 13 02:39:48 CST 2023
     */
    int updateByPrimaryKey(HistoryCloudNativeResult record);
}
