package com.hummer.auth.mapper;

import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface HummerLicenseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hummer_license
     *
     * @mbg.generated Mon May 15 23:28:02 CST 2023
     */
    long countByExample(HummerLicenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hummer_license
     *
     * @mbg.generated Mon May 15 23:28:02 CST 2023
     */
    int deleteByExample(HummerLicenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hummer_license
     *
     * @mbg.generated Mon May 15 23:28:02 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hummer_license
     *
     * @mbg.generated Mon May 15 23:28:02 CST 2023
     */
    int insert(HummerLicenseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hummer_license
     *
     * @mbg.generated Mon May 15 23:28:02 CST 2023
     */
    int insertSelective(HummerLicenseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hummer_license
     *
     * @mbg.generated Mon May 15 23:28:02 CST 2023
     */
    List<HummerLicenseWithBLOBs> selectByExampleWithBLOBs(HummerLicenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hummer_license
     *
     * @mbg.generated Mon May 15 23:28:02 CST 2023
     */
    List<HummerLicense> selectByExample(HummerLicenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hummer_license
     *
     * @mbg.generated Mon May 15 23:28:02 CST 2023
     */
    HummerLicenseWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hummer_license
     *
     * @mbg.generated Mon May 15 23:28:02 CST 2023
     */
    int updateByExampleSelective(@Param("record") HummerLicenseWithBLOBs record, @Param("example") HummerLicenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hummer_license
     *
     * @mbg.generated Mon May 15 23:28:02 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") HummerLicenseWithBLOBs record, @Param("example") HummerLicenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hummer_license
     *
     * @mbg.generated Mon May 15 23:28:02 CST 2023
     */
    int updateByExample(@Param("record") HummerLicense record, @Param("example") HummerLicenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hummer_license
     *
     * @mbg.generated Mon May 15 23:28:02 CST 2023
     */
    int updateByPrimaryKeySelective(HummerLicenseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hummer_license
     *
     * @mbg.generated Mon May 15 23:28:02 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(HummerLicenseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hummer_license
     *
     * @mbg.generated Mon May 15 23:28:02 CST 2023
     */
    int updateByPrimaryKey(HummerLicense record);
}
