package com.hummer.common.core.mapper;

import com.hummer.common.core.domain.CloudResourceItem;
import com.hummer.common.core.domain.CloudResourceItemExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CloudResourceItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_resource_item
     *
     * @mbg.generated Sat Oct 01 14:57:31 CST 2022
     */
    long countByExample(CloudResourceItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_resource_item
     *
     * @mbg.generated Sat Oct 01 14:57:31 CST 2022
     */
    int deleteByExample(CloudResourceItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_resource_item
     *
     * @mbg.generated Sat Oct 01 14:57:31 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_resource_item
     *
     * @mbg.generated Sat Oct 01 14:57:31 CST 2022
     */
    int insert(CloudResourceItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_resource_item
     *
     * @mbg.generated Sat Oct 01 14:57:31 CST 2022
     */
    int insertSelective(CloudResourceItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_resource_item
     *
     * @mbg.generated Sat Oct 01 14:57:31 CST 2022
     */
    List<CloudResourceItem> selectByExampleWithBLOBs(CloudResourceItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_resource_item
     *
     * @mbg.generated Sat Oct 01 14:57:31 CST 2022
     */
    List<CloudResourceItem> selectByExample(CloudResourceItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_resource_item
     *
     * @mbg.generated Sat Oct 01 14:57:31 CST 2022
     */
    CloudResourceItem selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_resource_item
     *
     * @mbg.generated Sat Oct 01 14:57:31 CST 2022
     */
    int updateByExampleSelective(@Param("record") CloudResourceItem record, @Param("example") CloudResourceItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_resource_item
     *
     * @mbg.generated Sat Oct 01 14:57:31 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") CloudResourceItem record, @Param("example") CloudResourceItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_resource_item
     *
     * @mbg.generated Sat Oct 01 14:57:31 CST 2022
     */
    int updateByExample(@Param("record") CloudResourceItem record, @Param("example") CloudResourceItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_resource_item
     *
     * @mbg.generated Sat Oct 01 14:57:31 CST 2022
     */
    int updateByPrimaryKeySelective(CloudResourceItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_resource_item
     *
     * @mbg.generated Sat Oct 01 14:57:31 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(CloudResourceItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_resource_item
     *
     * @mbg.generated Sat Oct 01 14:57:31 CST 2022
     */
    int updateByPrimaryKey(CloudResourceItem record);
}
