package com.hummer.common.core.mapper;

import com.hummer.common.core.domain.CloudNativeSourceRbacRelation;
import com.hummer.common.core.domain.CloudNativeSourceRbacRelationExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CloudNativeSourceRbacRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_rbac_relation
     *
     * @mbg.generated Sun Jan 15 19:47:50 CST 2023
     */
    long countByExample(CloudNativeSourceRbacRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_rbac_relation
     *
     * @mbg.generated Sun Jan 15 19:47:50 CST 2023
     */
    int deleteByExample(CloudNativeSourceRbacRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_rbac_relation
     *
     * @mbg.generated Sun Jan 15 19:47:50 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_rbac_relation
     *
     * @mbg.generated Sun Jan 15 19:47:50 CST 2023
     */
    int insert(CloudNativeSourceRbacRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_rbac_relation
     *
     * @mbg.generated Sun Jan 15 19:47:50 CST 2023
     */
    int insertSelective(CloudNativeSourceRbacRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_rbac_relation
     *
     * @mbg.generated Sun Jan 15 19:47:50 CST 2023
     */
    List<CloudNativeSourceRbacRelation> selectByExample(CloudNativeSourceRbacRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_rbac_relation
     *
     * @mbg.generated Sun Jan 15 19:47:50 CST 2023
     */
    CloudNativeSourceRbacRelation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_rbac_relation
     *
     * @mbg.generated Sun Jan 15 19:47:50 CST 2023
     */
    int updateByExampleSelective(@Param("record") CloudNativeSourceRbacRelation record, @Param("example") CloudNativeSourceRbacRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_rbac_relation
     *
     * @mbg.generated Sun Jan 15 19:47:50 CST 2023
     */
    int updateByExample(@Param("record") CloudNativeSourceRbacRelation record, @Param("example") CloudNativeSourceRbacRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_rbac_relation
     *
     * @mbg.generated Sun Jan 15 19:47:50 CST 2023
     */
    int updateByPrimaryKeySelective(CloudNativeSourceRbacRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_rbac_relation
     *
     * @mbg.generated Sun Jan 15 19:47:50 CST 2023
     */
    int updateByPrimaryKey(CloudNativeSourceRbacRelation record);
}
