package com.hummer.common.core.mapper;

import com.hummer.common.core.domain.CloudAccountQuartzTaskRelaLog;
import com.hummer.common.core.domain.CloudAccountQuartzTaskRelaLogExample;
import com.hummer.common.core.domain.CloudAccountQuartzTaskRelaLogWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CloudAccountQuartzTaskRelaLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_account_quartz_task_rela_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    long countByExample(CloudAccountQuartzTaskRelaLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_account_quartz_task_rela_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int deleteByExample(CloudAccountQuartzTaskRelaLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_account_quartz_task_rela_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_account_quartz_task_rela_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int insert(CloudAccountQuartzTaskRelaLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_account_quartz_task_rela_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int insertSelective(CloudAccountQuartzTaskRelaLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_account_quartz_task_rela_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    List<CloudAccountQuartzTaskRelaLogWithBLOBs> selectByExampleWithBLOBs(CloudAccountQuartzTaskRelaLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_account_quartz_task_rela_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    List<CloudAccountQuartzTaskRelaLog> selectByExample(CloudAccountQuartzTaskRelaLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_account_quartz_task_rela_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    CloudAccountQuartzTaskRelaLogWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_account_quartz_task_rela_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByExampleSelective(@Param("record") CloudAccountQuartzTaskRelaLogWithBLOBs record, @Param("example") CloudAccountQuartzTaskRelaLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_account_quartz_task_rela_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") CloudAccountQuartzTaskRelaLogWithBLOBs record, @Param("example") CloudAccountQuartzTaskRelaLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_account_quartz_task_rela_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByExample(@Param("record") CloudAccountQuartzTaskRelaLog record, @Param("example") CloudAccountQuartzTaskRelaLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_account_quartz_task_rela_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByPrimaryKeySelective(CloudAccountQuartzTaskRelaLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_account_quartz_task_rela_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(CloudAccountQuartzTaskRelaLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_account_quartz_task_rela_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByPrimaryKey(CloudAccountQuartzTaskRelaLog record);
}
