FROM registry.cn-beijing.aliyuncs.com/hummerrisk/nuclei:v0.9 as nuclei-env

FROM registry.cn-beijing.aliyuncs.com/hummerrisk/prowler:v0.9 as prowler-env

FROM registry.cn-beijing.aliyuncs.com/hummerrisk/xray:v0.9 as xray-env

WORKDIR /usr

COPY --from=nuclei-env /usr/local/bin/nuclei /usr/local/bin/nuclei

COPY --from=prowler-env /prowler /prowler

COPY --from=xray-env /opt/hummerrisk/xray/ /opt/hummerrisk/xray/

RUN apt-get update -y && apt-get install --yes git bash libpcap-dev musl && \
    pip3 install detect-secrets==1.0.3 && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install -i /usr/local/aws-cli -b /usr/local/bin && \
    mkdir -p /opt/apps

# 基础镜像
FROM  registry.cn-beijing.aliyuncs.com/hummerrisk/alpine:jre17
# author
MAINTAINER Hummer
ARG HR_VERSION=dev

COPY ./jar/hummer-modules-cloud.jar /opt/apps/hummer-modules-cloud.jar

ENV JAVA_APP_JAR=/opt/apps/hummer-modules-cloud.jar \
    AB_OFF=true \
    HR_VERSION=${HR_VERSION} \
    JAVA_OPTIONS="-Dfile.encoding=utf-8 -Djava.awt.headless=true -DHR_NACOS_SERVER_ADDR=127.0.0.1 -DHR_MYSQL_HOST=127.0.0.1 -DHR_MYSQL_PORT=3306 -DHR_MYSQL_DB=hummer_risk -DHR_MYSQL_USER=root -DHR_MYSQL_PASSWORD=root"

HEALTHCHECK --interval=15s --timeout=5s --retries=20 --start-period=30s CMD curl -f 127.0.0.1:9203

CMD ["/deployments/run-java.sh"]

EXPOSE 9203
