package io.hummerrisk.base.domain;

import java.io.Serializable;

public class MessageOrderItem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_order_item.id
     *
     * @mbg.generated Thu Mar 11 14:08:10 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_order_item.message_order_id
     *
     * @mbg.generated Thu Mar 11 14:08:10 CST 2021
     */
    private String messageOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_order_item.task_id
     *
     * @mbg.generated Thu Mar 11 14:08:10 CST 2021
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_order_item.task_name
     *
     * @mbg.generated Thu Mar 11 14:08:10 CST 2021
     */
    private String taskName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_order_item.status
     *
     * @mbg.generated Thu Mar 11 14:08:10 CST 2021
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_order_item.create_time
     *
     * @mbg.generated Thu Mar 11 14:08:10 CST 2021
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_order_item.send_time
     *
     * @mbg.generated Thu Mar 11 14:08:10 CST 2021
     */
    private Long sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message_order_item
     *
     * @mbg.generated Thu Mar 11 14:08:10 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_order_item.id
     *
     * @return the value of message_order_item.id
     *
     * @mbg.generated Thu Mar 11 14:08:10 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_order_item.id
     *
     * @param id the value for message_order_item.id
     *
     * @mbg.generated Thu Mar 11 14:08:10 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_order_item.message_order_id
     *
     * @return the value of message_order_item.message_order_id
     *
     * @mbg.generated Thu Mar 11 14:08:10 CST 2021
     */
    public String getMessageOrderId() {
        return messageOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_order_item.message_order_id
     *
     * @param messageOrderId the value for message_order_item.message_order_id
     *
     * @mbg.generated Thu Mar 11 14:08:10 CST 2021
     */
    public void setMessageOrderId(String messageOrderId) {
        this.messageOrderId = messageOrderId == null ? null : messageOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_order_item.task_id
     *
     * @return the value of message_order_item.task_id
     *
     * @mbg.generated Thu Mar 11 14:08:10 CST 2021
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_order_item.task_id
     *
     * @param taskId the value for message_order_item.task_id
     *
     * @mbg.generated Thu Mar 11 14:08:10 CST 2021
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_order_item.task_name
     *
     * @return the value of message_order_item.task_name
     *
     * @mbg.generated Thu Mar 11 14:08:10 CST 2021
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_order_item.task_name
     *
     * @param taskName the value for message_order_item.task_name
     *
     * @mbg.generated Thu Mar 11 14:08:10 CST 2021
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_order_item.status
     *
     * @return the value of message_order_item.status
     *
     * @mbg.generated Thu Mar 11 14:08:10 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_order_item.status
     *
     * @param status the value for message_order_item.status
     *
     * @mbg.generated Thu Mar 11 14:08:10 CST 2021
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_order_item.create_time
     *
     * @return the value of message_order_item.create_time
     *
     * @mbg.generated Thu Mar 11 14:08:10 CST 2021
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_order_item.create_time
     *
     * @param createTime the value for message_order_item.create_time
     *
     * @mbg.generated Thu Mar 11 14:08:10 CST 2021
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_order_item.send_time
     *
     * @return the value of message_order_item.send_time
     *
     * @mbg.generated Thu Mar 11 14:08:10 CST 2021
     */
    public Long getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_order_item.send_time
     *
     * @param sendTime the value for message_order_item.send_time
     *
     * @mbg.generated Thu Mar 11 14:08:10 CST 2021
     */
    public void setSendTime(Long sendTime) {
        this.sendTime = sendTime;
    }
}
