package io.hummerrisk.base.domain;

import java.io.Serializable;

public class PackageResultWithBLOBs extends PackageResult implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_result.resources
     *
     * @mbg.generated Wed Jun 08 02:46:46 CST 2022
     */
    private String resources;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_result.return_json
     *
     * @mbg.generated Wed Jun 08 02:46:46 CST 2022
     */
    private String returnJson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_result.return_log
     *
     * @mbg.generated Wed Jun 08 02:46:46 CST 2022
     */
    private String returnLog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table package_result
     *
     * @mbg.generated Wed Jun 08 02:46:46 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_result.resources
     *
     * @return the value of package_result.resources
     *
     * @mbg.generated Wed Jun 08 02:46:46 CST 2022
     */
    public String getResources() {
        return resources;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_result.resources
     *
     * @param resources the value for package_result.resources
     *
     * @mbg.generated Wed Jun 08 02:46:46 CST 2022
     */
    public void setResources(String resources) {
        this.resources = resources == null ? null : resources.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_result.return_json
     *
     * @return the value of package_result.return_json
     *
     * @mbg.generated Wed Jun 08 02:46:46 CST 2022
     */
    public String getReturnJson() {
        return returnJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_result.return_json
     *
     * @param returnJson the value for package_result.return_json
     *
     * @mbg.generated Wed Jun 08 02:46:46 CST 2022
     */
    public void setReturnJson(String returnJson) {
        this.returnJson = returnJson == null ? null : returnJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_result.return_log
     *
     * @return the value of package_result.return_log
     *
     * @mbg.generated Wed Jun 08 02:46:46 CST 2022
     */
    public String getReturnLog() {
        return returnLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_result.return_log
     *
     * @param returnLog the value for package_result.return_log
     *
     * @mbg.generated Wed Jun 08 02:46:46 CST 2022
     */
    public void setReturnLog(String returnLog) {
        this.returnLog = returnLog == null ? null : returnLog.trim();
    }
}
