package io.hummerrisk.base.domain;

import java.io.Serializable;

public class RuleInspectionReport implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_inspection_report.id
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_inspection_report.project
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    private String project;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_inspection_report.item_sort_first_level
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    private String itemSortFirstLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_inspection_report.item_sort_second_level
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    private String itemSortSecondLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_inspection_report.improvement
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    private String improvement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rule_inspection_report
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_inspection_report.id
     *
     * @return the value of rule_inspection_report.id
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_inspection_report.id
     *
     * @param id the value for rule_inspection_report.id
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_inspection_report.project
     *
     * @return the value of rule_inspection_report.project
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    public String getProject() {
        return project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_inspection_report.project
     *
     * @param project the value for rule_inspection_report.project
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    public void setProject(String project) {
        this.project = project == null ? null : project.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_inspection_report.item_sort_first_level
     *
     * @return the value of rule_inspection_report.item_sort_first_level
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    public String getItemSortFirstLevel() {
        return itemSortFirstLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_inspection_report.item_sort_first_level
     *
     * @param itemSortFirstLevel the value for rule_inspection_report.item_sort_first_level
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    public void setItemSortFirstLevel(String itemSortFirstLevel) {
        this.itemSortFirstLevel = itemSortFirstLevel == null ? null : itemSortFirstLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_inspection_report.item_sort_second_level
     *
     * @return the value of rule_inspection_report.item_sort_second_level
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    public String getItemSortSecondLevel() {
        return itemSortSecondLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_inspection_report.item_sort_second_level
     *
     * @param itemSortSecondLevel the value for rule_inspection_report.item_sort_second_level
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    public void setItemSortSecondLevel(String itemSortSecondLevel) {
        this.itemSortSecondLevel = itemSortSecondLevel == null ? null : itemSortSecondLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_inspection_report.improvement
     *
     * @return the value of rule_inspection_report.improvement
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    public String getImprovement() {
        return improvement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_inspection_report.improvement
     *
     * @param improvement the value for rule_inspection_report.improvement
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    public void setImprovement(String improvement) {
        this.improvement = improvement == null ? null : improvement.trim();
    }
}
