# 基础镜像
FROM nginx
# author
MAINTAINER Hummer

/projects/hummer-ui
# 创建目录
RUN mkdir -p /home/hummer/projects/hummer-ui
# 指定路径
WORKDIR /home/hummer/projects/hummer-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/hummer/projects/hummer-ui
