package com.hummer.common.mapper.mapper;

import com.hummer.common.core.domain.CloudNativeSourceSyncLog;
import com.hummer.common.core.domain.CloudNativeSourceSyncLogExample;
import com.hummer.common.core.domain.CloudNativeSourceSyncLogWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CloudNativeSourceSyncLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_sync_log
     *
     * @mbg.generated Sun Nov 13 00:23:30 CST 2022
     */
    long countByExample(CloudNativeSourceSyncLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_sync_log
     *
     * @mbg.generated Sun Nov 13 00:23:30 CST 2022
     */
    int deleteByExample(CloudNativeSourceSyncLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_sync_log
     *
     * @mbg.generated Sun Nov 13 00:23:30 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_sync_log
     *
     * @mbg.generated Sun Nov 13 00:23:30 CST 2022
     */
    int insert(CloudNativeSourceSyncLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_sync_log
     *
     * @mbg.generated Sun Nov 13 00:23:30 CST 2022
     */
    int insertSelective(CloudNativeSourceSyncLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_sync_log
     *
     * @mbg.generated Sun Nov 13 00:23:30 CST 2022
     */
    List<CloudNativeSourceSyncLogWithBLOBs> selectByExampleWithBLOBs(CloudNativeSourceSyncLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_sync_log
     *
     * @mbg.generated Sun Nov 13 00:23:30 CST 2022
     */
    List<CloudNativeSourceSyncLog> selectByExample(CloudNativeSourceSyncLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_sync_log
     *
     * @mbg.generated Sun Nov 13 00:23:30 CST 2022
     */
    CloudNativeSourceSyncLogWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_sync_log
     *
     * @mbg.generated Sun Nov 13 00:23:30 CST 2022
     */
    int updateByExampleSelective(@Param("record") CloudNativeSourceSyncLogWithBLOBs record, @Param("example") CloudNativeSourceSyncLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_sync_log
     *
     * @mbg.generated Sun Nov 13 00:23:30 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") CloudNativeSourceSyncLogWithBLOBs record, @Param("example") CloudNativeSourceSyncLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_sync_log
     *
     * @mbg.generated Sun Nov 13 00:23:30 CST 2022
     */
    int updateByExample(@Param("record") CloudNativeSourceSyncLog record, @Param("example") CloudNativeSourceSyncLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_sync_log
     *
     * @mbg.generated Sun Nov 13 00:23:30 CST 2022
     */
    int updateByPrimaryKeySelective(CloudNativeSourceSyncLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_sync_log
     *
     * @mbg.generated Sun Nov 13 00:23:30 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(CloudNativeSourceSyncLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_sync_log
     *
     * @mbg.generated Sun Nov 13 00:23:30 CST 2022
     */
    int updateByPrimaryKey(CloudNativeSourceSyncLog record);
}
