package com.hummer.common.mapper.mapper;

import com.hummer.common.core.domain.CloudNativeResultItem;
import com.hummer.common.core.domain.CloudNativeResultItemExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CloudNativeResultItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_result_item
     *
     * @mbg.generated Sun Nov 13 02:41:59 CST 2022
     */
    long countByExample(CloudNativeResultItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_result_item
     *
     * @mbg.generated Sun Nov 13 02:41:59 CST 2022
     */
    int deleteByExample(CloudNativeResultItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_result_item
     *
     * @mbg.generated Sun Nov 13 02:41:59 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_result_item
     *
     * @mbg.generated Sun Nov 13 02:41:59 CST 2022
     */
    int insert(CloudNativeResultItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_result_item
     *
     * @mbg.generated Sun Nov 13 02:41:59 CST 2022
     */
    int insertSelective(CloudNativeResultItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_result_item
     *
     * @mbg.generated Sun Nov 13 02:41:59 CST 2022
     */
    List<CloudNativeResultItem> selectByExampleWithBLOBs(CloudNativeResultItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_result_item
     *
     * @mbg.generated Sun Nov 13 02:41:59 CST 2022
     */
    List<CloudNativeResultItem> selectByExample(CloudNativeResultItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_result_item
     *
     * @mbg.generated Sun Nov 13 02:41:59 CST 2022
     */
    CloudNativeResultItem selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_result_item
     *
     * @mbg.generated Sun Nov 13 02:41:59 CST 2022
     */
    int updateByExampleSelective(@Param("record") CloudNativeResultItem record, @Param("example") CloudNativeResultItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_result_item
     *
     * @mbg.generated Sun Nov 13 02:41:59 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") CloudNativeResultItem record, @Param("example") CloudNativeResultItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_result_item
     *
     * @mbg.generated Sun Nov 13 02:41:59 CST 2022
     */
    int updateByExample(@Param("record") CloudNativeResultItem record, @Param("example") CloudNativeResultItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_result_item
     *
     * @mbg.generated Sun Nov 13 02:41:59 CST 2022
     */
    int updateByPrimaryKeySelective(CloudNativeResultItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_result_item
     *
     * @mbg.generated Sun Nov 13 02:41:59 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(CloudNativeResultItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_result_item
     *
     * @mbg.generated Sun Nov 13 02:41:59 CST 2022
     */
    int updateByPrimaryKey(CloudNativeResultItem record);
}
