package com.hummer.common.mapper.mapper;

import com.hummer.common.core.domain.CloudNativeSourceImage;
import com.hummer.common.core.domain.CloudNativeSourceImageExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CloudNativeSourceImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_image
     *
     * @mbg.generated Sat Nov 12 19:52:36 CST 2022
     */
    long countByExample(CloudNativeSourceImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_image
     *
     * @mbg.generated Sat Nov 12 19:52:36 CST 2022
     */
    int deleteByExample(CloudNativeSourceImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_image
     *
     * @mbg.generated Sat Nov 12 19:52:36 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_image
     *
     * @mbg.generated Sat Nov 12 19:52:36 CST 2022
     */
    int insert(CloudNativeSourceImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_image
     *
     * @mbg.generated Sat Nov 12 19:52:36 CST 2022
     */
    int insertSelective(CloudNativeSourceImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_image
     *
     * @mbg.generated Sat Nov 12 19:52:36 CST 2022
     */
    List<CloudNativeSourceImage> selectByExample(CloudNativeSourceImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_image
     *
     * @mbg.generated Sat Nov 12 19:52:36 CST 2022
     */
    CloudNativeSourceImage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_image
     *
     * @mbg.generated Sat Nov 12 19:52:36 CST 2022
     */
    int updateByExampleSelective(@Param("record") CloudNativeSourceImage record, @Param("example") CloudNativeSourceImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_image
     *
     * @mbg.generated Sat Nov 12 19:52:36 CST 2022
     */
    int updateByExample(@Param("record") CloudNativeSourceImage record, @Param("example") CloudNativeSourceImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_image
     *
     * @mbg.generated Sat Nov 12 19:52:36 CST 2022
     */
    int updateByPrimaryKeySelective(CloudNativeSourceImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_native_source_image
     *
     * @mbg.generated Sat Nov 12 19:52:36 CST 2022
     */
    int updateByPrimaryKey(CloudNativeSourceImage record);
}
