package com.hummer.common.mapper.mapper;

import com.hummer.common.core.domain.FileSystemRule;
import com.hummer.common.core.domain.FileSystemRuleExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FileSystemRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system_rule
     *
     * @mbg.generated Wed Oct 12 23:33:01 CST 2022
     */
    long countByExample(FileSystemRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system_rule
     *
     * @mbg.generated Wed Oct 12 23:33:01 CST 2022
     */
    int deleteByExample(FileSystemRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system_rule
     *
     * @mbg.generated Wed Oct 12 23:33:01 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system_rule
     *
     * @mbg.generated Wed Oct 12 23:33:01 CST 2022
     */
    int insert(FileSystemRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system_rule
     *
     * @mbg.generated Wed Oct 12 23:33:01 CST 2022
     */
    int insertSelective(FileSystemRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system_rule
     *
     * @mbg.generated Wed Oct 12 23:33:01 CST 2022
     */
    List<FileSystemRule> selectByExampleWithBLOBs(FileSystemRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system_rule
     *
     * @mbg.generated Wed Oct 12 23:33:01 CST 2022
     */
    List<FileSystemRule> selectByExample(FileSystemRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system_rule
     *
     * @mbg.generated Wed Oct 12 23:33:01 CST 2022
     */
    FileSystemRule selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system_rule
     *
     * @mbg.generated Wed Oct 12 23:33:01 CST 2022
     */
    int updateByExampleSelective(@Param("record") FileSystemRule record, @Param("example") FileSystemRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system_rule
     *
     * @mbg.generated Wed Oct 12 23:33:01 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") FileSystemRule record, @Param("example") FileSystemRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system_rule
     *
     * @mbg.generated Wed Oct 12 23:33:01 CST 2022
     */
    int updateByExample(@Param("record") FileSystemRule record, @Param("example") FileSystemRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system_rule
     *
     * @mbg.generated Wed Oct 12 23:33:01 CST 2022
     */
    int updateByPrimaryKeySelective(FileSystemRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system_rule
     *
     * @mbg.generated Wed Oct 12 23:33:01 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(FileSystemRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system_rule
     *
     * @mbg.generated Wed Oct 12 23:33:01 CST 2022
     */
    int updateByPrimaryKey(FileSystemRule record);
}
