package com.hummer.common.mapper.mapper;

import com.hummer.common.core.domain.HistoryVulnTaskResource;
import com.hummer.common.core.domain.HistoryVulnTaskResourceExample;
import com.hummer.common.core.domain.HistoryVulnTaskResourceWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface HistoryVulnTaskResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_vuln_task_resource
     *
     * @mbg.generated Thu Jul 21 18:34:03 CST 2022
     */
    long countByExample(HistoryVulnTaskResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_vuln_task_resource
     *
     * @mbg.generated Thu Jul 21 18:34:03 CST 2022
     */
    int deleteByExample(HistoryVulnTaskResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_vuln_task_resource
     *
     * @mbg.generated Thu Jul 21 18:34:03 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_vuln_task_resource
     *
     * @mbg.generated Thu Jul 21 18:34:03 CST 2022
     */
    int insert(HistoryVulnTaskResourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_vuln_task_resource
     *
     * @mbg.generated Thu Jul 21 18:34:03 CST 2022
     */
    int insertSelective(HistoryVulnTaskResourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_vuln_task_resource
     *
     * @mbg.generated Thu Jul 21 18:34:03 CST 2022
     */
    List<HistoryVulnTaskResourceWithBLOBs> selectByExampleWithBLOBs(HistoryVulnTaskResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_vuln_task_resource
     *
     * @mbg.generated Thu Jul 21 18:34:03 CST 2022
     */
    List<HistoryVulnTaskResource> selectByExample(HistoryVulnTaskResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_vuln_task_resource
     *
     * @mbg.generated Thu Jul 21 18:34:03 CST 2022
     */
    HistoryVulnTaskResourceWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_vuln_task_resource
     *
     * @mbg.generated Thu Jul 21 18:34:03 CST 2022
     */
    int updateByExampleSelective(@Param("record") HistoryVulnTaskResourceWithBLOBs record, @Param("example") HistoryVulnTaskResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_vuln_task_resource
     *
     * @mbg.generated Thu Jul 21 18:34:03 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") HistoryVulnTaskResourceWithBLOBs record, @Param("example") HistoryVulnTaskResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_vuln_task_resource
     *
     * @mbg.generated Thu Jul 21 18:34:03 CST 2022
     */
    int updateByExample(@Param("record") HistoryVulnTaskResource record, @Param("example") HistoryVulnTaskResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_vuln_task_resource
     *
     * @mbg.generated Thu Jul 21 18:34:03 CST 2022
     */
    int updateByPrimaryKeySelective(HistoryVulnTaskResourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_vuln_task_resource
     *
     * @mbg.generated Thu Jul 21 18:34:03 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(HistoryVulnTaskResourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_vuln_task_resource
     *
     * @mbg.generated Thu Jul 21 18:34:03 CST 2022
     */
    int updateByPrimaryKey(HistoryVulnTaskResource record);
}
