package com.hummer.common.mapper.mapper;

import com.hummer.common.core.domain.ImageResultLog;
import com.hummer.common.core.domain.ImageResultLogExample;
import com.hummer.common.core.domain.ImageResultLogWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ImageResultLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    long countByExample(ImageResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int deleteByExample(ImageResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int insert(ImageResultLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int insertSelective(ImageResultLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    List<ImageResultLogWithBLOBs> selectByExampleWithBLOBs(ImageResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    List<ImageResultLog> selectByExample(ImageResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    ImageResultLogWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByExampleSelective(@Param("record") ImageResultLogWithBLOBs record, @Param("example") ImageResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") ImageResultLogWithBLOBs record, @Param("example") ImageResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByExample(@Param("record") ImageResultLog record, @Param("example") ImageResultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByPrimaryKeySelective(ImageResultLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(ImageResultLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_result_log
     *
     * @mbg.generated Thu Oct 20 07:33:40 CST 2022
     */
    int updateByPrimaryKey(ImageResultLog record);
}
