package com.hummer.common.mapper.mapper;

import com.hummer.common.core.domain.OssLog;
import com.hummer.common.core.domain.OssLogExample;
import com.hummer.common.core.domain.OssLogWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OssLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_log
     *
     * @mbg.generated Sat Nov 12 01:59:11 CST 2022
     */
    long countByExample(OssLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_log
     *
     * @mbg.generated Sat Nov 12 01:59:11 CST 2022
     */
    int deleteByExample(OssLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_log
     *
     * @mbg.generated Sat Nov 12 01:59:11 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_log
     *
     * @mbg.generated Sat Nov 12 01:59:11 CST 2022
     */
    int insert(OssLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_log
     *
     * @mbg.generated Sat Nov 12 01:59:11 CST 2022
     */
    int insertSelective(OssLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_log
     *
     * @mbg.generated Sat Nov 12 01:59:11 CST 2022
     */
    List<OssLogWithBLOBs> selectByExampleWithBLOBs(OssLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_log
     *
     * @mbg.generated Sat Nov 12 01:59:11 CST 2022
     */
    List<OssLog> selectByExample(OssLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_log
     *
     * @mbg.generated Sat Nov 12 01:59:11 CST 2022
     */
    OssLogWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_log
     *
     * @mbg.generated Sat Nov 12 01:59:11 CST 2022
     */
    int updateByExampleSelective(@Param("record") OssLogWithBLOBs record, @Param("example") OssLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_log
     *
     * @mbg.generated Sat Nov 12 01:59:11 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") OssLogWithBLOBs record, @Param("example") OssLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_log
     *
     * @mbg.generated Sat Nov 12 01:59:11 CST 2022
     */
    int updateByExample(@Param("record") OssLog record, @Param("example") OssLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_log
     *
     * @mbg.generated Sat Nov 12 01:59:11 CST 2022
     */
    int updateByPrimaryKeySelective(OssLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_log
     *
     * @mbg.generated Sat Nov 12 01:59:11 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(OssLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_log
     *
     * @mbg.generated Sat Nov 12 01:59:11 CST 2022
     */
    int updateByPrimaryKey(OssLog record);
}
