package com.hummer.common.core.domain;

import java.io.Serializable;

public class CloudProject implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_project.id
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_project.status
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_project.account_name
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_project.account_id
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_project.plugin_id
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    private String pluginId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_project.plugin_name
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    private String pluginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_project.plugin_icon
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    private String pluginIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_project.creator
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_project.create_time
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_project.resources_sum
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    private Long resourcesSum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_project.return_sum
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    private Long returnSum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_project.job_type
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    private String jobType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_project.xxl_job_id
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    private Integer xxlJobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_project.xxl_job_id
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    private Integer scanScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cloud_project
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_project.id
     *
     * @return the value of cloud_project.id
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_project.id
     *
     * @param id the value for cloud_project.id
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_project.status
     *
     * @return the value of cloud_project.status
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_project.status
     *
     * @param status the value for cloud_project.status
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_project.account_name
     *
     * @return the value of cloud_project.account_name
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_project.account_name
     *
     * @param accountName the value for cloud_project.account_name
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_project.account_id
     *
     * @return the value of cloud_project.account_id
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_project.account_id
     *
     * @param accountId the value for cloud_project.account_id
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_project.plugin_id
     *
     * @return the value of cloud_project.plugin_id
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    public String getPluginId() {
        return pluginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_project.plugin_id
     *
     * @param pluginId the value for cloud_project.plugin_id
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    public void setPluginId(String pluginId) {
        this.pluginId = pluginId == null ? null : pluginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_project.plugin_name
     *
     * @return the value of cloud_project.plugin_name
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    public String getPluginName() {
        return pluginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_project.plugin_name
     *
     * @param pluginName the value for cloud_project.plugin_name
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    public void setPluginName(String pluginName) {
        this.pluginName = pluginName == null ? null : pluginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_project.plugin_icon
     *
     * @return the value of cloud_project.plugin_icon
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    public String getPluginIcon() {
        return pluginIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_project.plugin_icon
     *
     * @param pluginIcon the value for cloud_project.plugin_icon
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    public void setPluginIcon(String pluginIcon) {
        this.pluginIcon = pluginIcon == null ? null : pluginIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_project.creator
     *
     * @return the value of cloud_project.creator
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_project.creator
     *
     * @param creator the value for cloud_project.creator
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_project.create_time
     *
     * @return the value of cloud_project.create_time
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_project.create_time
     *
     * @param createTime the value for cloud_project.create_time
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_project.resources_sum
     *
     * @return the value of cloud_project.resources_sum
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    public Long getResourcesSum() {
        return resourcesSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_project.resources_sum
     *
     * @param resourcesSum the value for cloud_project.resources_sum
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    public void setResourcesSum(Long resourcesSum) {
        this.resourcesSum = resourcesSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_project.return_sum
     *
     * @return the value of cloud_project.return_sum
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    public Long getReturnSum() {
        return returnSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_project.return_sum
     *
     * @param returnSum the value for cloud_project.return_sum
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    public void setReturnSum(Long returnSum) {
        this.returnSum = returnSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_project.job_type
     *
     * @return the value of cloud_project.job_type
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    public String getJobType() {
        return jobType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_project.job_type
     *
     * @param jobType the value for cloud_project.job_type
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    public void setJobType(String jobType) {
        this.jobType = jobType == null ? null : jobType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_project.xxl_job_id
     *
     * @return the value of cloud_project.xxl_job_id
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    public Integer getXxlJobId() {
        return xxlJobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_project.xxl_job_id
     *
     * @param xxlJobId the value for cloud_project.xxl_job_id
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    public void setXxlJobId(Integer xxlJobId) {
        this.xxlJobId = xxlJobId;
    }

    public Integer getScanScore() {
        return scanScore;
    }

    public void setScanScore(Integer scanScore) {
        this.scanScore = scanScore;
    }
}