package com.hummer.common.core.domain;

import java.io.Serializable;

public class Oss implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss.id
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss.name
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss.endpoint
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    private String endpoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss.plugin_id
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    private String pluginId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss.plugin_name
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    private String pluginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss.plugin_icon
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    private String pluginIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss.status
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss.sync_status
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    private String syncStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss.create_time
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss.update_time
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    private Long updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss.creator
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss.proxy_id
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    private Integer proxyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss.sum
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    private Integer sum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss.account_id
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    private String accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oss
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss.id
     *
     * @return the value of oss.id
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss.id
     *
     * @param id the value for oss.id
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss.name
     *
     * @return the value of oss.name
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss.name
     *
     * @param name the value for oss.name
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss.endpoint
     *
     * @return the value of oss.endpoint
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    public String getEndpoint() {
        return endpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss.endpoint
     *
     * @param endpoint the value for oss.endpoint
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    public void setEndpoint(String endpoint) {
        this.endpoint = endpoint == null ? null : endpoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss.plugin_id
     *
     * @return the value of oss.plugin_id
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    public String getPluginId() {
        return pluginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss.plugin_id
     *
     * @param pluginId the value for oss.plugin_id
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    public void setPluginId(String pluginId) {
        this.pluginId = pluginId == null ? null : pluginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss.plugin_name
     *
     * @return the value of oss.plugin_name
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    public String getPluginName() {
        return pluginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss.plugin_name
     *
     * @param pluginName the value for oss.plugin_name
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    public void setPluginName(String pluginName) {
        this.pluginName = pluginName == null ? null : pluginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss.plugin_icon
     *
     * @return the value of oss.plugin_icon
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    public String getPluginIcon() {
        return pluginIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss.plugin_icon
     *
     * @param pluginIcon the value for oss.plugin_icon
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    public void setPluginIcon(String pluginIcon) {
        this.pluginIcon = pluginIcon == null ? null : pluginIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss.status
     *
     * @return the value of oss.status
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss.status
     *
     * @param status the value for oss.status
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss.sync_status
     *
     * @return the value of oss.sync_status
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    public String getSyncStatus() {
        return syncStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss.sync_status
     *
     * @param syncStatus the value for oss.sync_status
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    public void setSyncStatus(String syncStatus) {
        this.syncStatus = syncStatus == null ? null : syncStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss.create_time
     *
     * @return the value of oss.create_time
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss.create_time
     *
     * @param createTime the value for oss.create_time
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss.update_time
     *
     * @return the value of oss.update_time
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss.update_time
     *
     * @param updateTime the value for oss.update_time
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss.creator
     *
     * @return the value of oss.creator
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss.creator
     *
     * @param creator the value for oss.creator
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss.proxy_id
     *
     * @return the value of oss.proxy_id
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    public Integer getProxyId() {
        return proxyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss.proxy_id
     *
     * @param proxyId the value for oss.proxy_id
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    public void setProxyId(Integer proxyId) {
        this.proxyId = proxyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss.sum
     *
     * @return the value of oss.sum
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    public Integer getSum() {
        return sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss.sum
     *
     * @param sum the value for oss.sum
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    public void setSum(Integer sum) {
        this.sum = sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss.account_id
     *
     * @return the value of oss.account_id
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss.account_id
     *
     * @param accountId the value for oss.account_id
     *
     * @mbg.generated Wed Jul 19 22:45:54 CST 2023
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }
}
