package com.hummer.common.core.domain;

import java.io.Serializable;

public class ServerGroup implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_group.id
     *
     * @mbg.generated Wed May 25 23:33:49 CST 2022
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_group.name
     *
     * @mbg.generated Wed May 25 23:33:49 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_group.create_time
     *
     * @mbg.generated Wed May 25 23:33:49 CST 2022
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_group.update_time
     *
     * @mbg.generated Wed May 25 23:33:49 CST 2022
     */
    private Long updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_group.creator
     *
     * @mbg.generated Wed May 25 23:33:49 CST 2022
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table server_group
     *
     * @mbg.generated Wed May 25 23:33:49 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_group.id
     *
     * @return the value of server_group.id
     *
     * @mbg.generated Wed May 25 23:33:49 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_group.id
     *
     * @param id the value for server_group.id
     *
     * @mbg.generated Wed May 25 23:33:49 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_group.name
     *
     * @return the value of server_group.name
     *
     * @mbg.generated Wed May 25 23:33:49 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_group.name
     *
     * @param name the value for server_group.name
     *
     * @mbg.generated Wed May 25 23:33:49 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_group.create_time
     *
     * @return the value of server_group.create_time
     *
     * @mbg.generated Wed May 25 23:33:49 CST 2022
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_group.create_time
     *
     * @param createTime the value for server_group.create_time
     *
     * @mbg.generated Wed May 25 23:33:49 CST 2022
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_group.update_time
     *
     * @return the value of server_group.update_time
     *
     * @mbg.generated Wed May 25 23:33:49 CST 2022
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_group.update_time
     *
     * @param updateTime the value for server_group.update_time
     *
     * @mbg.generated Wed May 25 23:33:49 CST 2022
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_group.creator
     *
     * @return the value of server_group.creator
     *
     * @mbg.generated Wed May 25 23:33:49 CST 2022
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_group.creator
     *
     * @param creator the value for server_group.creator
     *
     * @mbg.generated Wed May 25 23:33:49 CST 2022
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }
}
