package com.hummer.cloud.mapper;

import com.hummer.common.core.domain.CloudProjectLog;
import com.hummer.common.core.domain.CloudProjectLogExample;
import com.hummer.common.core.domain.CloudProjectLogWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CloudProjectLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_project_log
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    long countByExample(CloudProjectLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_project_log
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    int deleteByExample(CloudProjectLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_project_log
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_project_log
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    int insert(CloudProjectLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_project_log
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    int insertSelective(CloudProjectLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_project_log
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    List<CloudProjectLogWithBLOBs> selectByExampleWithBLOBs(CloudProjectLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_project_log
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    List<CloudProjectLog> selectByExample(CloudProjectLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_project_log
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    CloudProjectLogWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_project_log
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    int updateByExampleSelective(@Param("record") CloudProjectLogWithBLOBs record, @Param("example") CloudProjectLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_project_log
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") CloudProjectLogWithBLOBs record, @Param("example") CloudProjectLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_project_log
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    int updateByExample(@Param("record") CloudProjectLog record, @Param("example") CloudProjectLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_project_log
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    int updateByPrimaryKeySelective(CloudProjectLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_project_log
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(CloudProjectLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_project_log
     *
     * @mbg.generated Fri Aug 11 15:18:52 CST 2023
     */
    int updateByPrimaryKey(CloudProjectLog record);
}