package com.hummer.cloud.mapper;

import com.hummer.common.core.domain.CloudTask;
import com.hummer.common.core.domain.CloudTaskExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CloudTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_task
     *
     * @mbg.generated Mon Aug 21 11:17:47 CST 2023
     */
    long countByExample(CloudTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_task
     *
     * @mbg.generated Mon Aug 21 11:17:47 CST 2023
     */
    int deleteByExample(CloudTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_task
     *
     * @mbg.generated Mon Aug 21 11:17:47 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_task
     *
     * @mbg.generated Mon Aug 21 11:17:47 CST 2023
     */
    int insert(CloudTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_task
     *
     * @mbg.generated Mon Aug 21 11:17:47 CST 2023
     */
    int insertSelective(CloudTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_task
     *
     * @mbg.generated Mon Aug 21 11:17:47 CST 2023
     */
    List<CloudTask> selectByExampleWithBLOBs(CloudTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_task
     *
     * @mbg.generated Mon Aug 21 11:17:47 CST 2023
     */
    List<CloudTask> selectByExample(CloudTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_task
     *
     * @mbg.generated Mon Aug 21 11:17:47 CST 2023
     */
    CloudTask selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_task
     *
     * @mbg.generated Mon Aug 21 11:17:47 CST 2023
     */
    int updateByExampleSelective(@Param("record") CloudTask record, @Param("example") CloudTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_task
     *
     * @mbg.generated Mon Aug 21 11:17:47 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") CloudTask record, @Param("example") CloudTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_task
     *
     * @mbg.generated Mon Aug 21 11:17:47 CST 2023
     */
    int updateByExample(@Param("record") CloudTask record, @Param("example") CloudTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_task
     *
     * @mbg.generated Mon Aug 21 11:17:47 CST 2023
     */
    int updateByPrimaryKeySelective(CloudTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_task
     *
     * @mbg.generated Mon Aug 21 11:17:47 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(CloudTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_task
     *
     * @mbg.generated Mon Aug 21 11:17:47 CST 2023
     */
    int updateByPrimaryKey(CloudTask record);
}