package com.hummer.cloud.mapper;

import com.hummer.common.core.domain.CloudResourceRela;
import com.hummer.common.core.domain.CloudResourceRelaExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CloudResourceRelaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_resource_rela
     *
     * @mbg.generated Thu Jun 29 23:06:03 CST 2023
     */
    long countByExample(CloudResourceRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_resource_rela
     *
     * @mbg.generated Thu Jun 29 23:06:03 CST 2023
     */
    int deleteByExample(CloudResourceRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_resource_rela
     *
     * @mbg.generated Thu Jun 29 23:06:03 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_resource_rela
     *
     * @mbg.generated Thu Jun 29 23:06:03 CST 2023
     */
    int insert(CloudResourceRela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_resource_rela
     *
     * @mbg.generated Thu Jun 29 23:06:03 CST 2023
     */
    int insertSelective(CloudResourceRela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_resource_rela
     *
     * @mbg.generated Thu Jun 29 23:06:03 CST 2023
     */
    List<CloudResourceRela> selectByExample(CloudResourceRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_resource_rela
     *
     * @mbg.generated Thu Jun 29 23:06:03 CST 2023
     */
    CloudResourceRela selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_resource_rela
     *
     * @mbg.generated Thu Jun 29 23:06:03 CST 2023
     */
    int updateByExampleSelective(@Param("record") CloudResourceRela record, @Param("example") CloudResourceRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_resource_rela
     *
     * @mbg.generated Thu Jun 29 23:06:03 CST 2023
     */
    int updateByExample(@Param("record") CloudResourceRela record, @Param("example") CloudResourceRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_resource_rela
     *
     * @mbg.generated Thu Jun 29 23:06:03 CST 2023
     */
    int updateByPrimaryKeySelective(CloudResourceRela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_resource_rela
     *
     * @mbg.generated Thu Jun 29 23:06:03 CST 2023
     */
    int updateByPrimaryKey(CloudResourceRela record);
}
