package com.hummer.cloud.mapper;

import com.hummer.common.core.domain.Oss;
import com.hummer.common.core.domain.OssExample;
import com.hummer.common.core.domain.OssWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OssMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss
     *
     * @mbg.generated Thu Jul 06 01:30:21 CST 2023
     */
    long countByExample(OssExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss
     *
     * @mbg.generated Thu Jul 06 01:30:21 CST 2023
     */
    int deleteByExample(OssExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss
     *
     * @mbg.generated Thu Jul 06 01:30:21 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss
     *
     * @mbg.generated Thu Jul 06 01:30:21 CST 2023
     */
    int insert(OssWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss
     *
     * @mbg.generated Thu Jul 06 01:30:21 CST 2023
     */
    int insertSelective(OssWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss
     *
     * @mbg.generated Thu Jul 06 01:30:21 CST 2023
     */
    List<OssWithBLOBs> selectByExampleWithBLOBs(OssExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss
     *
     * @mbg.generated Thu Jul 06 01:30:21 CST 2023
     */
    List<Oss> selectByExample(OssExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss
     *
     * @mbg.generated Thu Jul 06 01:30:21 CST 2023
     */
    OssWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss
     *
     * @mbg.generated Thu Jul 06 01:30:21 CST 2023
     */
    int updateByExampleSelective(@Param("record") OssWithBLOBs record, @Param("example") OssExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss
     *
     * @mbg.generated Thu Jul 06 01:30:21 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") OssWithBLOBs record, @Param("example") OssExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss
     *
     * @mbg.generated Thu Jul 06 01:30:21 CST 2023
     */
    int updateByExample(@Param("record") Oss record, @Param("example") OssExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss
     *
     * @mbg.generated Thu Jul 06 01:30:21 CST 2023
     */
    int updateByPrimaryKeySelective(OssWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss
     *
     * @mbg.generated Thu Jul 06 01:30:21 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(OssWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss
     *
     * @mbg.generated Thu Jul 06 01:30:21 CST 2023
     */
    int updateByPrimaryKey(Oss record);
}
