package com.hummer.cloud.mapper;

import com.hummer.common.core.domain.ReportResult;
import com.hummer.common.core.domain.ReportResultExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ReportResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_result
     *
     * @mbg.generated Mon May 15 07:46:00 CST 2023
     */
    long countByExample(ReportResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_result
     *
     * @mbg.generated Mon May 15 07:46:00 CST 2023
     */
    int deleteByExample(ReportResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_result
     *
     * @mbg.generated Mon May 15 07:46:00 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_result
     *
     * @mbg.generated Mon May 15 07:46:00 CST 2023
     */
    int insert(ReportResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_result
     *
     * @mbg.generated Mon May 15 07:46:00 CST 2023
     */
    int insertSelective(ReportResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_result
     *
     * @mbg.generated Mon May 15 07:46:00 CST 2023
     */
    List<ReportResult> selectByExampleWithBLOBs(ReportResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_result
     *
     * @mbg.generated Mon May 15 07:46:00 CST 2023
     */
    List<ReportResult> selectByExample(ReportResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_result
     *
     * @mbg.generated Mon May 15 07:46:00 CST 2023
     */
    ReportResult selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_result
     *
     * @mbg.generated Mon May 15 07:46:00 CST 2023
     */
    int updateByExampleSelective(@Param("record") ReportResult record, @Param("example") ReportResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_result
     *
     * @mbg.generated Mon May 15 07:46:00 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") ReportResult record, @Param("example") ReportResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_result
     *
     * @mbg.generated Mon May 15 07:46:00 CST 2023
     */
    int updateByExample(@Param("record") ReportResult record, @Param("example") ReportResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_result
     *
     * @mbg.generated Mon May 15 07:46:00 CST 2023
     */
    int updateByPrimaryKeySelective(ReportResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_result
     *
     * @mbg.generated Mon May 15 07:46:00 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(ReportResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_result
     *
     * @mbg.generated Mon May 15 07:46:00 CST 2023
     */
    int updateByPrimaryKey(ReportResult record);
}
