package com.hummer.cloud.mapper;

import com.hummer.common.core.domain.Resource;
import com.hummer.common.core.domain.ResourceExample;
import com.hummer.common.core.domain.ResourceWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Mon Jun 20 01:10:06 CST 2022
     */
    long countByExample(ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Mon Jun 20 01:10:06 CST 2022
     */
    int deleteByExample(ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Mon Jun 20 01:10:06 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Mon Jun 20 01:10:06 CST 2022
     */
    int insert(ResourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Mon Jun 20 01:10:06 CST 2022
     */
    int insertSelective(ResourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Mon Jun 20 01:10:06 CST 2022
     */
    List<ResourceWithBLOBs> selectByExampleWithBLOBs(ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Mon Jun 20 01:10:06 CST 2022
     */
    List<Resource> selectByExample(ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Mon Jun 20 01:10:06 CST 2022
     */
    ResourceWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Mon Jun 20 01:10:06 CST 2022
     */
    int updateByExampleSelective(@Param("record") ResourceWithBLOBs record, @Param("example") ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Mon Jun 20 01:10:06 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") ResourceWithBLOBs record, @Param("example") ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Mon Jun 20 01:10:06 CST 2022
     */
    int updateByExample(@Param("record") Resource record, @Param("example") ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Mon Jun 20 01:10:06 CST 2022
     */
    int updateByPrimaryKeySelective(ResourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Mon Jun 20 01:10:06 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(ResourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Mon Jun 20 01:10:06 CST 2022
     */
    int updateByPrimaryKey(Resource record);
}
