package com.hummer.cloud.mapper;

import com.hummer.common.core.domain.RuleAccountParameter;
import com.hummer.common.core.domain.RuleAccountParameterExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RuleAccountParameterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_account_parameter
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    long countByExample(RuleAccountParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_account_parameter
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    int deleteByExample(RuleAccountParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_account_parameter
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_account_parameter
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    int insert(RuleAccountParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_account_parameter
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    int insertSelective(RuleAccountParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_account_parameter
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    List<RuleAccountParameter> selectByExampleWithBLOBs(RuleAccountParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_account_parameter
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    List<RuleAccountParameter> selectByExample(RuleAccountParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_account_parameter
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    RuleAccountParameter selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_account_parameter
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    int updateByExampleSelective(@Param("record") RuleAccountParameter record, @Param("example") RuleAccountParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_account_parameter
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") RuleAccountParameter record, @Param("example") RuleAccountParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_account_parameter
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    int updateByExample(@Param("record") RuleAccountParameter record, @Param("example") RuleAccountParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_account_parameter
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    int updateByPrimaryKeySelective(RuleAccountParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_account_parameter
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(RuleAccountParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_account_parameter
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    int updateByPrimaryKey(RuleAccountParameter record);
}
