# 基础镜像
FROM  registry.cn-beijing.aliyuncs.com/hummerrisk/alpine:jdk17
# author
MAINTAINER Hummer


# 创建目录
RUN mkdir -p /home/hummer
# 指定路径
WORKDIR /home/hummer
# 复制jar文件到路径
COPY ./jar/hummer-modules-k8s.jar /home/hummer/hummer-modules-k8s.jar
# 启动云原生服务
ENTRYPOINT ["java","-jar","hummer-modules-k8s.jar"]
