package io.hummerrisk.base.mapper;

import io.hummerrisk.base.domain.MessageTask;
import io.hummerrisk.base.domain.MessageTaskExample;
import io.hummerrisk.base.domain.MessageTaskWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MessageTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_task
     *
     * @mbg.generated Fri Apr 23 14:19:17 CST 2021
     */
    long countByExample(MessageTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_task
     *
     * @mbg.generated Fri Apr 23 14:19:17 CST 2021
     */
    int deleteByExample(MessageTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_task
     *
     * @mbg.generated Fri Apr 23 14:19:17 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_task
     *
     * @mbg.generated Fri Apr 23 14:19:17 CST 2021
     */
    int insert(MessageTaskWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_task
     *
     * @mbg.generated Fri Apr 23 14:19:17 CST 2021
     */
    int insertSelective(MessageTaskWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_task
     *
     * @mbg.generated Fri Apr 23 14:19:17 CST 2021
     */
    List<MessageTaskWithBLOBs> selectByExampleWithBLOBs(MessageTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_task
     *
     * @mbg.generated Fri Apr 23 14:19:17 CST 2021
     */
    List<MessageTask> selectByExample(MessageTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_task
     *
     * @mbg.generated Fri Apr 23 14:19:17 CST 2021
     */
    MessageTaskWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_task
     *
     * @mbg.generated Fri Apr 23 14:19:17 CST 2021
     */
    int updateByExampleSelective(@Param("record") MessageTaskWithBLOBs record, @Param("example") MessageTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_task
     *
     * @mbg.generated Fri Apr 23 14:19:17 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") MessageTaskWithBLOBs record, @Param("example") MessageTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_task
     *
     * @mbg.generated Fri Apr 23 14:19:17 CST 2021
     */
    int updateByExample(@Param("record") MessageTask record, @Param("example") MessageTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_task
     *
     * @mbg.generated Fri Apr 23 14:19:17 CST 2021
     */
    int updateByPrimaryKeySelective(MessageTaskWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_task
     *
     * @mbg.generated Fri Apr 23 14:19:17 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(MessageTaskWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_task
     *
     * @mbg.generated Fri Apr 23 14:19:17 CST 2021
     */
    int updateByPrimaryKey(MessageTask record);
}
