package io.hummerrisk.base.mapper;

import io.hummerrisk.base.domain.TaskItem;
import io.hummerrisk.base.domain.TaskItemExample;
import io.hummerrisk.base.domain.TaskItemWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TaskItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_item
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    long countByExample(TaskItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_item
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    int deleteByExample(TaskItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_item
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_item
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    int insert(TaskItemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_item
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    int insertSelective(TaskItemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_item
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    List<TaskItemWithBLOBs> selectByExampleWithBLOBs(TaskItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_item
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    List<TaskItem> selectByExample(TaskItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_item
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    TaskItemWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_item
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    int updateByExampleSelective(@Param("record") TaskItemWithBLOBs record, @Param("example") TaskItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_item
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") TaskItemWithBLOBs record, @Param("example") TaskItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_item
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    int updateByExample(@Param("record") TaskItem record, @Param("example") TaskItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_item
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    int updateByPrimaryKeySelective(TaskItemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_item
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(TaskItemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_item
     *
     * @mbg.generated Tue Jan 19 17:40:09 CST 2022
     */
    int updateByPrimaryKey(TaskItem record);
}
