# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER hummer

# 挂载目录
VOLUME /home/hummer
# 创建目录
RUN mkdir -p /home/hummer
# 指定路径
WORKDIR /home/hummer
# 复制jar文件到路径
COPY ./jar/hummer-modules-system.jar /home/hummer/hummer-modules-system.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","hummer-modules-system.jar"]
