package com.hummer.common.core.constant;

public enum ResourceTypeConstants {
    USER,
    ROLE,
    ORGANIZATION,
    WORKSPACE,
    CLOUD_ACCOUNT,
    CLOUD_PROJECT,
    CLOUD_NATIVE,
    CLOUD_NATIVE_CONFIG,
    RULE,
    RULE_TAG,
    RULE_GROUP,
    RESOURCE,
    TASK,
    SYSTEM,
    QUOTA,
    PROXY,
    SERVER,
    IMAGE,
    CODE,
    SBOM,
    SBOM_VERSION,
    SYNC,
    FILE_SYSTEM,
    OSS,
    WEBHOOK,
    REPORT_CENTER,
}
