# 基础镜像
FROM registry.cn-beijing.aliyuncs.com/hummerrisk/alpine:jdk17
# author
MAINTAINER Hummer


# 创建目录
RUN mkdir -p /home/hummer
# 指定路径
WORKDIR /home/hummer
# 复制jar文件到路径
COPY ./jar/hummer-visual-monitor.jar /home/hummer/hummer-visual-monitor.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","hummer-visual-monitor.jar"]
