package com.hummer.k8s.mapper;

import com.hummer.common.core.domain.ServerLynisResultDetail;
import com.hummer.common.core.domain.ServerLynisResultDetailExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ServerLynisResultDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_lynis_result_detail
     *
     * @mbg.generated Thu May 11 20:47:06 CST 2023
     */
    long countByExample(ServerLynisResultDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_lynis_result_detail
     *
     * @mbg.generated Thu May 11 20:47:06 CST 2023
     */
    int deleteByExample(ServerLynisResultDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_lynis_result_detail
     *
     * @mbg.generated Thu May 11 20:47:06 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_lynis_result_detail
     *
     * @mbg.generated Thu May 11 20:47:06 CST 2023
     */
    int insert(ServerLynisResultDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_lynis_result_detail
     *
     * @mbg.generated Thu May 11 20:47:06 CST 2023
     */
    int insertSelective(ServerLynisResultDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_lynis_result_detail
     *
     * @mbg.generated Thu May 11 20:47:06 CST 2023
     */
    List<ServerLynisResultDetail> selectByExampleWithBLOBs(ServerLynisResultDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_lynis_result_detail
     *
     * @mbg.generated Thu May 11 20:47:06 CST 2023
     */
    List<ServerLynisResultDetail> selectByExample(ServerLynisResultDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_lynis_result_detail
     *
     * @mbg.generated Thu May 11 20:47:06 CST 2023
     */
    ServerLynisResultDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_lynis_result_detail
     *
     * @mbg.generated Thu May 11 20:47:06 CST 2023
     */
    int updateByExampleSelective(@Param("record") ServerLynisResultDetail record, @Param("example") ServerLynisResultDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_lynis_result_detail
     *
     * @mbg.generated Thu May 11 20:47:06 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") ServerLynisResultDetail record, @Param("example") ServerLynisResultDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_lynis_result_detail
     *
     * @mbg.generated Thu May 11 20:47:06 CST 2023
     */
    int updateByExample(@Param("record") ServerLynisResultDetail record, @Param("example") ServerLynisResultDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_lynis_result_detail
     *
     * @mbg.generated Thu May 11 20:47:06 CST 2023
     */
    int updateByPrimaryKeySelective(ServerLynisResultDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_lynis_result_detail
     *
     * @mbg.generated Thu May 11 20:47:06 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(ServerLynisResultDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_lynis_result_detail
     *
     * @mbg.generated Thu May 11 20:47:06 CST 2023
     */
    int updateByPrimaryKey(ServerLynisResultDetail record);
}
