# 基础镜像
FROM  registry.cn-beijing.aliyuncs.com/hummerrisk/alpine:jre17
# author
MAINTAINER Hummer
ARG HR_VERSION=dev

COPY ./jar/hummer-flyway.jar /opt/apps/hummer-flyway.jar

ENV JAVA_APP_JAR=/opt/apps/hummer-flyway.jar \
    AB_OFF=true \
    HR_VERSION=${HR_VERSION} \
    JAVA_OPTIONS="-Dfile.encoding=utf-8 -Djava.awt.headless=true -DHR_MYSQL_HOST=127.0.0.1 -DHR_MYSQL_PORT=3306 -DHR_MYSQL_DB_NACOS=hummer_config -DHR_MYSQL_USER=root -DHR_MYSQL_PASSWORD=root"

HEALTHCHECK --interval=15s --timeout=5s --retries=20 --start-period=30s CMD curl -f 127.0.0.1:9000

CMD ["/deployments/run-java.sh"]

EXPOSE 9000
